// ============================================================
// KAPLET ACADEMY — Catalogo Corsi
// ============================================================

const ROLES = [
  "Onboarding | AV","Onboarding | NET","Onboarding | SEC",
  "Pre-Sales | AV","Pre-Sales | NET","Pre-Sales | SEC","DOC | Agente",
  "Engineer AV | Junior","Engineer AV | Senior","Engineer AV | Video Specialist",
  "Engineer AV | Audio Specialist","Engineer AV | Collaboration Specialist",
  "Engineer NET | Junior","Engineer NET | Senior","Engineer NET | Network Specialist",
  "Engineer NET | Wireless Specialist","Engineer NET | Firewall Specialist",
  "Engineer SEC | Junior","Engineer SEC | Senior","Project Manager","Field Technician"
];

const BRAND_COLORS = {
  "AVIXA":"#F59E0B","DANTE":"#EF4444","NDI":"#38BDF8","AXIS":"#4ADE80",
  "FORTINET":"#F87171","CISCO":"#22D3EE","CRESTRON":"#4ADE80",
  "BARCO CTRL":"#FB923C","BARCO VIDEO":"#FBBF24","NOVASTAR":"#C084FC",
  "MILESTONE":"#F472B6","ALTA ACCESS":"#38BDF8","ALTA VIDEO":"#60A5FA",
  "AVIGILON UNITY":"#818CF8","SHURE":"#A78BFA","Q-SYS":"#F87171",
  "YAMAHA":"#FCD34D","POWERSOFT":"#34D399","TELEVIC":"#A78BFA",
  "EXTRON":"#F87171","K-ARRAY":"#4ADE80","K-SCAPE":"#34D399",
  "BRIGHTSIGN":"#60A5FA","ELMO":"#FCA5A1","KSENIA":"#C084FC",
  "NOTIFIER":"#FB923C","TECNOFIRE":"#F87171","KNX & DALI":"#818CF8","MAXHUB":"#38BDF8"
};

const PORTALS = {
  "AVIXA":          {url:"https://www.avixa.org/training-section/online-training",      note:"Portal ufficiale AVIXA"},
  "DANTE":          {url:"https://www.audinate.com/learning/training-certification/dante-certification-program", note:"Certificazioni L1–L3, DDM, Mastery"},
  "NDI":            {url:"https://community.ndi.video/course/index.php?categoryid=9",   note:"NDI Connected Community"},
  "AXIS":           {url:"https://www.axis.com/learning/learning-portal",               note:"Axis Communications Academy"},
  "FORTINET":       {url:"https://training.fortinet.com",                               note:"Fortinet Training Institute — NSE 1–7"},
  "CISCO":          {url:"https://u.cisco.com",                                         note:"Cisco U. — CCST, CCNA, CCNP, CCIE"},
  "CRESTRON":       {url:"https://www.crestron.com/Training-Events/Training",           note:"Crestron Technical Institute"},
  "AVIGILON UNITY": {url:"https://learning.motorolasolutions.com",                      note:"Motorola Solutions Learning Center"},
  "ALTA VIDEO":     {url:"https://learning.motorolasolutions.com",                      note:"Motorola Solutions Learning Center"},
  "ALTA ACCESS":    {url:"https://learning.motorolasolutions.com",                      note:"Motorola Solutions Learning Center"},
  "MILESTONE":      {url:"https://learn.milestonesys.com",                              note:"Milestone Partner Learning Portal"},
  "SHURE":          {url:"https://academy.shure.com",                                   note:"Shure Academy (SAI)"},
  "Q-SYS":          {url:"https://training.qsc.com",                                    note:"Q-SYS Training Portal — gratuito"},
  "YAMAHA":         {url:"https://audioversity.yamaha.com",                             note:"Audioversity Online — Yamaha Pro Audio"},
  "EXTRON":         {url:"https://www.extron.com/training/",                            note:"Extron Institute"},
  "NOVASTAR":       {url:"https://nce.novastar.tech",                                   note:"NCE — NovaStar Certified Engineer"},
  "BARCO CTRL":     {url:"https://www.barco.com/en/support/clickshare/training",        note:"Barco Training"},
  "BARCO VIDEO":    {url:"https://www.barco.com/en/support/clickshare/training",        note:"Barco Training"},
  "KNX & DALI":     {url:"https://www.knx.org/knx-en/for-professionals/get-started/knx-training/index.php", note:"KNX Association Training"},
  "ELMO":           {url:"https://www.elmosecurity.it",                                 note:"Sito ufficiale ELMO Security"},
  "KSENIA":         {url:"https://www.kseniasecurity.com",                              note:"Sito ufficiale Ksenia Security"},
  "TECNOFIRE":      {url:"https://www.tecnofire.eu",                                    note:"Sito ufficiale Tecnofire"},
  "NOTIFIER":       {url:"https://www.notifier.com/training",                           note:"Notifier Training"},
  "BRIGHTSIGN":     {url:"https://brightsign.biz/training",                             note:"BrightSign Training & Certification"},
  "MAXHUB":         {url:"https://www.maxhub.com/en/training/",                         note:"MAXHUB Training"},
  "POWERSOFT":      {url:"https://www.powersoft.com/en/support/training/",              note:"Powersoft Training"},
  "TELEVIC":        {url:"https://www.televic-conference.com/en/training",              note:"Televic Conference Training"},
  "K-ARRAY":        {url:"https://www.k-array.com/en/training/",                        note:"K-Array Training"},
  "K-SCAPE":        {url:"https://www.k-array.com/en/training/",                        note:"K-Scape Training"},
};

const COURSES = [
  {brand:"AVIXA",cat:"Foundation 60",name:"QuickStart: Onboarding the AV Industry",desc:"Corso introduttivo per chi è nuovo nel settore AV.",delivery:"E-Learning",dur:"10:00",price:0,roles:[0,7]},
  {brand:"AVIXA",cat:"Foundation 60",name:"Networking Technology",desc:"Networking applicato al mondo AV: Ethernet, IP networking, modello OSI.",delivery:"E-Learning",dur:"24:00",price:0,roles:[0,1,2,7]},
  {brand:"AVIXA",cat:"Foundation 60",name:"AVIXA-Recognized AV Technologist Test",desc:"Test online 100 domande su terminologia AV. Superamento all'80%.",delivery:"Test",dur:"02:00",price:0,roles:[0,7]},
  {brand:"AVIXA",cat:"AV 101",name:"AV Math",desc:"Matematica applicata al mondo AV: aspect ratio, legge di Ohm, decibel.",delivery:"E-Learning",dur:"15:00",price:0,roles:[7]},
  {brand:"AVIXA",cat:"AV 101",name:"AVoIP Foundations",desc:"Introduzione ad AVoIP: trasporto contenuti AV su reti IP.",delivery:"E-Learning",dur:"12:00",price:0,roles:[7]},
  {brand:"AVIXA",cat:"AV 101",name:"CTS 1: AV Technology",desc:"Fondamentali tecnologia AV per CTS.",delivery:"E-Learning",dur:"24:00",price:0,roles:[7]},
  {brand:"AVIXA",cat:"AV 101",name:"CTS 2: Applied AV and AV Project Process",desc:"Project management, installazione e troubleshooting.",delivery:"E-Learning",dur:"24:00",price:0,roles:[7]},
  {brand:"AVIXA",cat:"PRS 201",name:"AV Design 1: Environment Online",desc:"Tradurre i bisogni del cliente in un design concreto.",delivery:"E-Learning",dur:"24:00",price:0,roles:[3]},
  {brand:"AVIXA",cat:"PRS 201",name:"AV Design 2: Infrastructure Online",desc:"Infrastruttura per la progettazione AV.",delivery:"E-Learning",dur:"24:00",price:0,roles:[3]},
  {brand:"AVIXA",cat:"PRS 201",name:"AV Design 3: Applied Design Online",desc:"Segnali digitali, reti AV, multicast, sicurezza.",delivery:"E-Learning",dur:"24:00",price:0,roles:[3]},
  {brand:"AVIXA",cat:"PRS 202",name:"Audiovisual Network Professional Certification",desc:"Certificazione AVIXA ANP. Esame Pearson VUE.",delivery:"Certification",dur:"02:30",price:250,roles:[3]},
  {brand:"DANTE",cat:"",name:"Dante Certification Level 1",desc:"Fondamenti audio digitale, networking, Dante Controller.",delivery:"Certification",dur:"",price:0,roles:[2,4,7,8,11]},
  {brand:"DANTE",cat:"",name:"Dante Certification Level 2",desc:"Reti gestite, QoS, VLAN, IGMP, ridondanza.",delivery:"Certification",dur:"",price:0,roles:[2,4,7,9,11]},
  {brand:"DANTE",cat:"",name:"Dante Certification Level 3",desc:"Deployment enterprise, PTP, automazione API.",delivery:"Certification",dur:"",price:0,roles:[9,18]},
  {brand:"DANTE",cat:"",name:"Dante Domain Manager Administrator",desc:"Gestione avanzata DDM: domini, clocking, utenti.",delivery:"Certification",dur:"",price:0,roles:[16]},
  {brand:"DANTE",cat:"",name:"Dante Mastery Certification",desc:"4 giorni in presenza. Livello massimo.",delivery:"Certification",dur:"32:00",price:2000,roles:[16]},
  {brand:"NDI",cat:"",name:"NDI Basics",desc:"Fondamenti NDI e AV over IP.",delivery:"Certification",dur:"",price:0,roles:[2,4,7,9]},
  {brand:"NDI",cat:"",name:"NDI Professional",desc:"NDI avanzato: reti multi-switch, multicast, troubleshooting.",delivery:"Certification",dur:"",price:25,roles:[9]},
  {brand:"NDI",cat:"",name:"NDI Tools",desc:"Suite gratuita NDI Tools.",delivery:"Certification",dur:"",price:0,roles:[7,9]},
  {brand:"KNX & DALI",cat:"",name:"Corso Base Ohmega Progettazioni",desc:"Corso KNX e DALI: bus di comunicazione.",delivery:"In-Class",dur:"08:00",price:700,roles:[4,7]},
  {brand:"AVIGILON UNITY",cat:"Unity Video8",name:"Avigilon Unity Video8 E-Learning",desc:"Installazione e manutenzione sistema Avigilon Unity Video.",delivery:"E-Learning",dur:"21:00",price:0,roles:[19,20]},
  {brand:"AVIGILON UNITY",cat:"Pre Sales",name:"Avigilon Unity Video – Pre Sales & Sales",desc:"Presentazione prodotti e costruzione progetti.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,6,19,20]},
  {brand:"ALTA VIDEO",cat:"",name:"Avigilon Alta Video – Configuration and Operation",desc:"Piattaforma Avigilon Alta Video per installer.",delivery:"E-Learning",dur:"04:00",price:0,roles:[19,20]},
  {brand:"ALTA VIDEO",cat:"",name:"Alta Video – Pre Sales & Sales",desc:"Presentazione prodotti in presenza.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,6,19,20]},
  {brand:"ALTA ACCESS",cat:"",name:"Avigilon Alta Access – Installation and Configuration",desc:"Installazione e configurazione Alta Access.",delivery:"E-Learning",dur:"05:00",price:0,roles:[19,20]},
  {brand:"ALTA ACCESS",cat:"",name:"Alta Access – Pre Sales & Sales",desc:"Presentazione prodotti in presenza.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,6,19,20]},
  {brand:"AXIS",cat:"SEC 101",name:"Get to know network technology",desc:"Fondamenti networking: Ethernet, cavo, PoE.",delivery:"E-Learning",dur:"00:40",price:0,roles:[5,6,18,19]},
  {brand:"AXIS",cat:"SEC 101",name:"Get to know lighting for video surveillance",desc:"Luce vs qualità immagini: visibile, IR.",delivery:"E-Learning",dur:"00:15",price:0,roles:[5,6,18,19]},
  {brand:"AXIS",cat:"SEC 101",name:"Get to know image quality optimization",desc:"Risoluzione, sensori, frame rate, esposizione.",delivery:"E-Learning",dur:"00:15",price:0,roles:[5,6,18,19]},
  {brand:"AXIS",cat:"SEC 101",name:"Get to know Axis naming convention",desc:"Come leggere i codici prodotto Axis.",delivery:"E-Learning",dur:"00:30",price:0,roles:[5,6,18,19]},
  {brand:"AXIS",cat:"",name:"A&E – Progettazione soluzioni video di rete",desc:"Progettazione avanzata sistemi video Axis.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,19]},
  {brand:"AXIS",cat:"",name:"Analitiche Video Avanzate",desc:"Analitiche video avanzate Axis.",delivery:"In-Class",dur:"08:00",price:0,roles:[20]},
  {brand:"AXIS",cat:"",name:"AXIS Perimeter Defender",desc:"Protezione perimetrale avanzata.",delivery:"In-Class",dur:"08:00",price:0,roles:[20]},
  {brand:"BARCO CTRL",cat:"Control Room Specialist",name:"Barco CTRL Sales Specialist",desc:"Piattaforma KVM over IP Barco CTRL.",delivery:"E-Learning",dur:"00:20",price:0,roles:[3,5,8]},
  {brand:"BARCO CTRL",cat:"Control Room Specialist",name:"Barco CTRL Technical Associate",desc:"Installazione, configurazione base.",delivery:"E-Learning",dur:"01:30",price:0,roles:[9]},
  {brand:"BARCO CTRL",cat:"Control Room Specialist",name:"Barco CTRL Technical Expert",desc:"Certificazione avanzata: troubleshooting, log analysis.",delivery:"Certification",dur:"16:00",price:1400,roles:[9]},
  {brand:"BARCO CTRL",cat:"Control Room Specialist",name:"Barco UniSee",desc:"Certificazione videowall LCD bezel-less.",delivery:"Certification",dur:"16:00",price:1400,roles:[9]},
  {brand:"BARCO VIDEO",cat:"Image Processor",name:"Technical Introduction – Event Master",desc:"Panoramica tecnica sistemi Event Master.",delivery:"E-Learning",dur:"01:00",price:0,roles:[3,5,8]},
  {brand:"BARCO VIDEO",cat:"Image Processor",name:"E2 Gen2 – Certified Specialist",desc:"Event Master live event. Certificazione Barco 2 anni.",delivery:"Certification",dur:"32:00",price:2000,roles:[9]},
  {brand:"BARCO VIDEO",cat:"Image Processor",name:"E2 Gen2 Level 2 – Expert",desc:"Event Master E2 Gen2 avanzato.",delivery:"Certification",dur:"24:00",price:2400,roles:[9]},
  {brand:"BARCO VIDEO",cat:"",name:"Event Master Encore3 Certified Specialist",desc:"Corso Barco Encore3.",delivery:"Certification",dur:"24:00",price:1400,roles:[9]},
  {brand:"BRIGHTSIGN",cat:"",name:"brightAuthor connected 101",desc:"Utilizzo dei BrightSign.",delivery:"E-Learning",dur:"04:00",price:0,roles:[8]},
  {brand:"CISCO",cat:"Foundation",name:"Black Belt New Hire",desc:"Percorso introduttivo Cisco per nuovi assunti.",delivery:"E-Learning",dur:"",price:0,roles:[0,1,2]},
  {brand:"CISCO",cat:"Foundation",name:"Black Belt – Collaboration",desc:"Percorso Black Belt collaboration. Min 25 moduli.",delivery:"E-Learning",dur:"",price:0,roles:[3,6,7]},
  {brand:"CISCO",cat:"Foundation",name:"Black Belt – Networking",desc:"Percorso Black Belt networking. Min 25 moduli.",delivery:"E-Learning",dur:"",price:0,roles:[4,5,14]},
  {brand:"CISCO",cat:"",name:"CCST Networking",desc:"Entry-level Cisco: networking, help desk.",delivery:"Certification",dur:"",price:125,roles:[5,7,14]},
  {brand:"CISCO",cat:"",name:"CCNA",desc:"Certificazione networking fondamentale. Valida 3 anni.",delivery:"Certification",dur:"",price:300,roles:[13]},
  {brand:"CISCO",cat:"",name:"CCNP Collaboration",desc:"Collaboration, endpoint, call control avanzato.",delivery:"Certification",dur:"",price:400,roles:[12]},
  {brand:"CISCO",cat:"",name:"CCNP Enterprise",desc:"Reti enterprise avanzate.",delivery:"Certification",dur:"",price:400,roles:[14]},
  {brand:"CISCO",cat:"",name:"CCNP Wireless",desc:"Wi-Fi 6, Wi-Fi 7, Meraki.",delivery:"Certification",dur:"",price:400,roles:[15]},
  {brand:"CISCO",cat:"",name:"CCIE Enterprise",desc:"Certificazione expert reti enterprise.",delivery:"Certification",dur:"",price:400,roles:[14]},
  {brand:"CRESTRON",cat:"",name:"Crestron Basics – Commercial",desc:"Conferencing, AV over IP, XiO Cloud.",delivery:"E-Learning",dur:"",price:0,roles:[3,5,7]},
  {brand:"CRESTRON",cat:"",name:"DM NVX Technology – Certified Designer",desc:"Sistemi AVoIP con DM NVX.",delivery:"E-Learning",dur:"",price:0,roles:[9]},
  {brand:"CRESTRON",cat:"",name:"DM NVX Technology – Certified Engineer",desc:"Deployment e troubleshooting Crestron AVoIP.",delivery:"E-Learning",dur:"",price:0,roles:[9]},
  {brand:"CRESTRON",cat:"",name:"Intelligent Video – Certified Designer",desc:"Automate VX design. Certificazione IVC-D.",delivery:"E-Learning",dur:"",price:0,roles:[3,11]},
  {brand:"CRESTRON",cat:"",name:"Intelligent Video – Certified Engineer",desc:"Automate VX commissioning. Certificazione IVC-E.",delivery:"E-Learning",dur:"",price:0,roles:[11]},
  {brand:"ELMO",cat:"",name:"Elmo Security",desc:"Percorso Tecnico/Pre-Sales configurazione prodotti.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,6,19,20]},
  {brand:"EXTRON",cat:"",name:"AV Associate",desc:"Certificazione introduttiva AV.",delivery:"E-Learning",dur:"27:00",price:0,roles:[0,3,5]},
  {brand:"EXTRON",cat:"",name:"ProDSP Specialist",desc:"Sistemi audio Extron ProDSP.",delivery:"E-Learning",dur:"",price:0,roles:[8]},
  {brand:"EXTRON",cat:"",name:"NetworkAV Specialist (NAVS)",desc:"Sistemi AV over IP Extron NAV.",delivery:"In-Class",dur:"",price:0,roles:[9]},
  {brand:"FORTINET",cat:"",name:"NSE 1+2 | Certified Fundamentals Cybersecurity",desc:"Cybersecurity di base.",delivery:"Certification",dur:"",price:0,roles:[4,17]},
  {brand:"FORTINET",cat:"",name:"NSE 3 | FortiGate Operator",desc:"Policy sicurezza, VPN, controllo accessi.",delivery:"Certification",dur:"06:30",price:0,roles:[17]},
  {brand:"FORTINET",cat:"",name:"NSE 4+5 | Certified Professional – Network Security",desc:"Deployment firewall, analisi traffico.",delivery:"Certification",dur:"",price:0,roles:[17]},
  {brand:"FORTINET",cat:"",name:"NSE 6+7 | Certified Specialist – Network Security",desc:"Infrastrutture sicurezza enterprise.",delivery:"Certification",dur:"",price:0,roles:[18]},
  {brand:"K-ARRAY",cat:"",name:"K-ARRAY Certified Designer",desc:"Certificazione progettisti K-Array.",delivery:"E-Learning",dur:"24:00",price:0,roles:[3]},
  {brand:"K-ARRAY",cat:"",name:"K-ARRAY Certified Installer",desc:"Certificazione installatori K-Array.",delivery:"E-Learning",dur:"24:00",price:0,roles:[3,5]},
  {brand:"K-SCAPE",cat:"",name:"KSCAPE Corporate",desc:"K-Scape in ambito Corporate.",delivery:"E-Learning",dur:"01:00",price:0,roles:[3]},
  {brand:"KSENIA",cat:"",name:"Ksenia Security",desc:"Percorso Tecnico/Pre-Sales configurazione prodotti.",delivery:"In-Class",dur:"16:00",price:0,roles:[5,6,19,20]},
  {brand:"MILESTONE",cat:"Specialist Design",name:"XProtect Certified Design Engineer (XCDE)",desc:"Progettazione XProtect: architettura, licenze, cybersecurity.",delivery:"E-Learning",dur:"16:00",price:850,roles:[5,6,19,20]},
  {brand:"MILESTONE",cat:"Specialist Level 1",name:"XProtect Certified Integration Technician (XCIT)",desc:"XProtect 100–500 telecamere.",delivery:"E-Learning",dur:"24:00",price:1000,roles:[19,20]},
  {brand:"MILESTONE",cat:"Specialist Level 2",name:"XProtect Certified Integration Engineer (XCIE)",desc:"XProtect 100–10.000 telecamere.",delivery:"E-Learning",dur:"24:00",price:1500,roles:[20]},
  {brand:"NOTIFIER",cat:"",name:"Notifier – Programmazione Base",desc:"Programmazione base centrale Notifier.",delivery:"In-Class",dur:"08:00",price:0,roles:[19,20]},
  {brand:"NOTIFIER",cat:"",name:"Notifier – Programmazione Avanzata",desc:"Programmazione avanzata centrale Notifier.",delivery:"In-Class",dur:"08:00",price:0,roles:[20]},
  {brand:"NOVASTAR",cat:"NCE Level 1",name:"LED Screen Technician",desc:"Architettura LED, NovaLCT base.",delivery:"E-Learning",dur:"",price:0,roles:[3,5,7]},
  {brand:"NOVASTAR",cat:"NCE Level 2",name:"Professional in LED Screen Solution Design",desc:"Architetture avanzate, topologie.",delivery:"In-Class",dur:"",price:0,roles:[9]},
  {brand:"NOVASTAR",cat:"LED Specialist",name:"Specialist in LED Screen Solution Design",desc:"Multi-sending card, integrazione LED/LCD.",delivery:"In-Class",dur:"",price:0,roles:[9]},
  {brand:"POWERSOFT",cat:"",name:"Powersoft 101i",desc:"ArmoníaPlus: progetto Install.",delivery:"E-Learning",dur:"03:00",price:0,roles:[8]},
  {brand:"POWERSOFT",cat:"",name:"Powersoft 201i",desc:"Sistemi Install avanzati, networking.",delivery:"E-Learning",dur:"03:00",price:0,roles:[9]},
  {brand:"Q-SYS",cat:"",name:"Q-SYS Level 0",desc:"Corso introduttivo Q-SYS.",delivery:"E-Learning",dur:"",price:0,roles:[7,8]},
  {brand:"Q-SYS",cat:"",name:"Q-SYS Level 1",desc:"Core Manager, UCI, conferencing.",delivery:"E-Learning",dur:"08:00",price:0,roles:[7,8]},
  {brand:"Q-SYS",cat:"",name:"Q-SYS Level 2",desc:"Deployment pratico, networking, controllo.",delivery:"In-Class (Prase)",dur:"16:00",price:0,roles:[9]},
  {brand:"Q-SYS",cat:"",name:"Q-SYS Quantum – Control 101",desc:"Basi programmazione ecosistema Q-SYS.",delivery:"In-Class",dur:"03:00",price:0,roles:[8]},
  {brand:"SHURE",cat:"",name:"Collaboration & Conferencing Certification – Level 1",desc:"Infrastrutture AV/IT per meeting.",delivery:"Certification",dur:"08:00",price:0,roles:[3,5,7]},
  {brand:"SHURE",cat:"",name:"Collaboration & Conferencing Certification – Level 2",desc:"Progettazione avanzata sistemi AV/IT.",delivery:"Certification",dur:"08:00",price:0,roles:[9]},
  {brand:"SHURE",cat:"",name:"Pro Level 1",desc:"Fondamenti audio.",delivery:"Certification",dur:"04:30",price:0,roles:[8]},
  {brand:"SHURE",cat:"",name:"Pro Level 2",desc:"Audio engineer: sistemi live.",delivery:"Certification",dur:"07:00",price:0,roles:[9]},
  {brand:"SHURE",cat:"",name:"Pro Level 3",desc:"RF coordinator, system designer.",delivery:"Certification",dur:"14:00",price:0,roles:[11]},
  {brand:"TECNOFIRE",cat:"",name:"Tecnofire – Pre-Sales",desc:"Pre-Sales con normativa antincendio.",delivery:"In-Class",dur:"08:00",price:0,roles:[5,6,19,20]},
  {brand:"TECNOFIRE",cat:"",name:"Tecnofire – Tecnico Livello 1",desc:"Programmazione avanzata Centrale Incendio.",delivery:"In-Class",dur:"08:00",price:0,roles:[19,20]},
  {brand:"TELEVIC",cat:"",name:"Meeting Fundamentals",desc:"Fondamenti sistemi di conferenza.",delivery:"E-Learning",dur:"01:00",price:0,roles:[8]},
  {brand:"TELEVIC",cat:"",name:"Televic Foundation",desc:"Portfolio Televic per conferencing.",delivery:"E-Learning",dur:"01:00",price:0,roles:[8]},
  {brand:"YAMAHA",cat:"Beginner",name:"Sound and Hearing Basics",desc:"Produzione del suono, onde, percezione.",delivery:"E-Learning",dur:"00:30",price:0,roles:[3,8]},
  {brand:"YAMAHA",cat:"Beginner",name:"Yamaha Certified ProAV Specialist – Level 1",desc:"Sistema audio, abbinamento diffusori. AVIXA CTS RU.",delivery:"E-Learning",dur:"01:00",price:0,roles:[3,8]},
  {brand:"YAMAHA",cat:"",name:"DM3 Series: Digital Mixing Console",desc:"Streaming, live sound, networking.",delivery:"E-Learning",dur:"01:30",price:0,roles:[3,8]},
  {brand:"YAMAHA",cat:"",name:"DM7 Series: Digital Mixing Console",desc:"GUI, setup, networking Dante.",delivery:"E-Learning",dur:"03:00",price:0,roles:[3,8]},
];
