-- Kaplet Academy — Catalogo corsi in database
--
-- Porta i 183 corsi da js/courses.js dentro Postgres, così l'admin può
-- aggiungerli, modificarli ed eliminarli dal pannello senza toccare il codice.
-- Aggiunge anche `link`: la pagina del vendor dove si legge il programma
-- del corso e ci si iscrive.
--
-- Sicuro da rieseguire: la tabella si crea solo se manca e gli inserimenti
-- sono upsert sull'id, quindi un secondo Run non duplica nulla.
-- I corsi eliminati dal pannello NON vengono cancellati davvero: si mette
-- attivo = false, così le certificazioni e le assegnazioni già registrate
-- continuano a trovare il loro corso.

-- ============================================================
-- 1. Tabella
-- ============================================================
create table if not exists public.corsi_catalogo (
  id            text primary key,
  brand         text not null,
  gruppo        text,
  nome          text not null,
  descrizione   text,
  erogazione    text,
  durata        text,
  prezzo        numeric,
  link          text,
  paths         text[] not null default '{}',
  attivo        boolean not null default true,
  creato_il     timestamptz not null default now(),
  aggiornato_il timestamptz not null default now()
);

comment on table  public.corsi_catalogo             is 'Catalogo corsi Kaplet Academy: la sorgente unica per index, tecnico e admin';
comment on column public.corsi_catalogo.id          is 'Codice corso, es. KU-C-001. Lo genera il pannello se non lo scrivi';
comment on column public.corsi_catalogo.nome        is 'Chiave testuale con cui il corso compare in certificazioni.corso e corsi_assegnati.corso';
comment on column public.corsi_catalogo.link        is 'Pagina del corso sul sito del vendor';
comment on column public.corsi_catalogo.paths       is 'Percorsi/ruoli a cui il corso appartiene, es. {core_net,adv_eng_net}';
comment on column public.corsi_catalogo.attivo      is 'false = ritirato dal catalogo, resta per storico';

create index if not exists idx_corsi_catalogo_brand  on public.corsi_catalogo (brand);
create index if not exists idx_corsi_catalogo_attivo on public.corsi_catalogo (attivo) where attivo;
create index if not exists idx_corsi_catalogo_paths  on public.corsi_catalogo using gin (paths);

-- Tiene aggiornato aggiornato_il a ogni modifica
create or replace function public.tocca_corsi_catalogo()
returns trigger language plpgsql as $$
begin
  new.aggiornato_il := now();
  return new;
end $$;

drop trigger if exists trg_tocca_corsi_catalogo on public.corsi_catalogo;
create trigger trg_tocca_corsi_catalogo
  before update on public.corsi_catalogo
  for each row execute function public.tocca_corsi_catalogo();

-- ============================================================
-- 2. Permessi: tutti i loggati leggono, solo gli admin scrivono
-- ============================================================
alter table public.corsi_catalogo enable row level security;

drop policy if exists "catalogo leggibile dai loggati" on public.corsi_catalogo;
create policy "catalogo leggibile dai loggati"
  on public.corsi_catalogo for select
  to authenticated
  using (true);

drop policy if exists "catalogo scrivibile dagli admin" on public.corsi_catalogo;
create policy "catalogo scrivibile dagli admin"
  on public.corsi_catalogo for all
  to authenticated
  using (
    exists (
      select 1 from public.tecnici t
      where t.id = auth.uid() and t.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.tecnici t
      where t.id = auth.uid() and t.is_admin = true
    )
  );

-- ============================================================
-- 3. I 183 corsi
--    on conflict: rilanciare lo script riallinea i campi generati
--    dall'Excel ma NON tocca link e attivo, che si curano dal pannello.
-- ============================================================
insert into public.corsi_catalogo
  (id, brand, gruppo, nome, descrizione, erogazione, durata, prezzo, paths) values
  ('KU-C-001', 'AVIXA', 'AV101', 'QuickStart: Onboarding the AV Industry', 'È un corso introduttivo on-demand pensato per chi è nuovo nel settore AV (audiovisivo). Offre una panoramica rapida su organizzazioni del settore, ruoli professionali, tecnologie AV, segmenti di mercato e basi dei sistemi audiovisivi, con lezioni online interattive, video ed esercitazioni. L’obiettivo è aiutare chi parte da zero a capire come funziona l’industria e a orientare il proprio percorso professionale. Si segue in autonomia, al proprio ritmo.', 'E-Learning', '10:00', 0, array['core_av','core_field']),
  ('KU-C-002', 'AVIXA', 'NET101', 'Networking Technology', 'È un corso online on-demand dedicato alle basi del networking applicato al mondo AV. Spiega in modo pratico Ethernet, IP networking, modello OSI, protocolli di trasporto AV, sicurezza di rete, configurazioni tipiche e troubleshooting, con l’obiettivo di dare ai professionisti AV il linguaggio e le competenze essenziali per dialogare meglio con l’IT e gestire sistemi AV over IP.', 'E-Learning', '24:00', 0, array['core_av','core_net','core_field']),
  ('KU-E-001', 'AVIXA', null, 'AVIXA-Recognized AV Technologist Test', null, 'Test', '02:00', null, '{}'),
  ('KU-C-003', 'AVIXA', 'AV101', 'What is Color Temperature and why is it important?', 'È un breve corso on-demand di taglio introduttivo che spiega che cos’è la temperatura colore e perché è importante nel mondo AV, aiutando a capire come influisce sulla resa visiva e sulla qualità percepita delle immagini.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-004', 'AVIXA', 'AV101', 'Video Signal and Transportation', 'È un breve corso on-demand di taglio introduttivo dedicato ai segnali video e alla loro trasmissione, utile per capire la natura del video signal e la sua importanza nel settore AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-005', 'AVIXA', 'AV101', 'SPL & Weighting Curves', 'È un breve corso on-demand di taglio introduttivo che spiega il rapporto tra SPL, curve di pesatura e udito umano, aiutando a capire perché questi parametri sono importanti nella valutazione e gestione dell’audio in ambito AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-006', 'AVIXA', 'AV101', 'Sound System Equalizing', 'È un breve corso on-demand di taglio introduttivo dedicato alle basi dell’equalizzazione di un sistema audio, utile per capire come intervenire sull’EQ per ottimizzare la resa sonora di un impianto.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-007', 'AVIXA', 'AV101', 'Sizing Displays', 'È un breve corso on-demand di taglio introduttivo dedicato al dimensionamento dei display, utile per capire come scegliere uno schermo in base alla dimensione del display e dell’area di installazione o visione.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-008', 'AVIXA', 'AV101', 'Setting Power Amplifier Input Levels', 'È un breve corso on-demand di taglio introduttivo dedicato alla corretta impostazione della sensibilità d’ingresso dei power amplifier, utile per capire come regolare il livello dell’amplificatore in modo da garantire una migliore esperienza AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-009', 'AVIXA', 'AV101', 'PISCR Explained', 'È un breve corso on-demand di taglio introduttivo che spiega che cos’è il PISCR e perché un buon contrasto è fondamentale nei sistemi AV a proiezione, aiutando a capire meglio la qualità visiva delle immagini proiettate.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-010', 'AVIXA', 'AV101', 'Microphone Types and Polar Patterns', 'È un breve corso on-demand di taglio introduttivo dedicato ai tipi di microfono e ai diagrammi polari, utile per capire le principali tipologie costruttive e come la direttività influisce sulla ripresa del suono nei sistemi AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-011', 'AVIXA', 'AV101', 'Microphone Sensitivity', 'È un breve corso on-demand di taglio introduttivo che spiega che cos’è la sensibilità di un microfono e perché è importante, aiutando a capire come questo parametro influisce sulla corretta acquisizione del segnale audio nei sistemi AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-012', 'AVIXA', 'AV101', 'Loudspeaker Polar Patterns and Frequency Response', 'È un breve corso on-demand di taglio introduttivo dedicato ai diagrammi polari dei diffusori e alla risposta in frequenza, utile per capire come leggere le specifiche tecniche di un loudspeaker e valutarne meglio il comportamento acustico.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-013', 'AVIXA', 'AV101', 'Inverse Square Law', 'È un breve corso on-demand di taglio introduttivo dedicato alla legge dell’inverso del quadrato, utile per capire in modo visivo come varia il livello di energia o pressione sonora all’aumentare della distanza dalla sorgente nei sistemi AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-014', 'AVIXA', 'AV101', 'How to calculate Aspect Ratio', 'È un breve corso on-demand di taglio introduttivo che spiega come calcolare l’aspect ratio e come scegliere il display corretto in base al rapporto tra formato dello schermo e risoluzione.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-015', 'AVIXA', 'AV101', 'How Loud Should my Audio System Be?', 'È un breve corso on-demand di taglio introduttivo dedicato a come stabilire quanto deve essere “forte” un sistema audio, utile per capire se l’ascoltatore riesce davvero a percepire correttamente il segnale in base alle variabili dell’impianto.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-016', 'AVIXA', 'AV101', 'Ohm''s Law and Circuit Theory', 'È un breve corso on-demand di taglio introduttivo dedicato alla legge di Ohm e alla teoria dei circuiti, utile per capire i principi elettrici di base che stanno dietro al funzionamento dei sistemi AV.', 'Video', '00:10', 0, array['core_av','core_doc','core_field']),
  ('KU-C-017', 'AVIXA', 'AV101', 'Fundamentals of Optical Image Capture', 'È un breve corso on-demand di taglio introduttivo dedicato ai fondamenti dell’acquisizione ottica dell’immagine, utile per capire in modo semplice come vengono catturate le immagini nei sistemi video e AV.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-018', 'AVIXA', 'AV101', 'Frequency, Wavelength, and Amplitude', 'È un breve corso on-demand di taglio introduttivo dedicato a frequenza, lunghezza d’onda e ampiezza, utile per capire i tre componenti fondamentali delle onde sonore e luminose nel contesto AV.', 'Video', '00:10', 0, array['core_av','core_doc']),
  ('KU-C-019', 'AVIXA', 'AV101', 'Calculating Projection Throw Distance', 'È un breve corso on-demand di taglio introduttivo dedicato al calcolo della distanza di proiezione, utile per capire quali formule usare per determinare il corretto posizionamento del proiettore rispetto allo schermo.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-020', 'AVIXA', 'AV101', 'ROI and LED Display System Designs', 'È un breve corso on-demand di taglio introduttivo dedicato al ROI e alla progettazione di sistemi LED display, utile per capire come consulenti, designer e clienti possano valutare il modo migliore di utilizzare un nuovo LED wall per massimizzarne il ritorno sull’investimento.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-021', 'AVIXA', 'AV101', 'Wi-Fi RF Spectrum Analysis', 'È un breve corso on-demand di taglio introduttivo dedicato all’analisi dello spettro RF del Wi-Fi, utile per capire in modo semplice come il segnale Wi-Fi si propaga dal router ai dispositivi e quali elementi incidono sulla qualità della connessione in ambito AV.', 'Video', '00:10', 0, array['core_av']),
  ('KU-C-022', 'AVIXA', 'AV101', 'AV Math', 'È un corso on-demand dedicato alla matematica applicata al mondo AV, utile per rafforzare le competenze di base e saperle usare in casi pratici come aspect ratio, dimensionamento dei display, scale, legge di Ohm, calcoli di potenza e variazioni in decibel.', 'E-Learning', '15:00', 0, array['core_av','core_doc']),
  ('KU-C-023', 'AVIXA', 'AV101', 'AVoIP Foundations', 'È un corso on-demand introduttivo su AVoIP (AV over IP), utile per capire come i contenuti AV vengano trasportati su reti IP standard e quali aspetti tecnici vadano considerati prima, durante e dopo l’implementazione di una soluzione. È incluso nel track General Knowledge, vale 12 RU ed è gratuito per i membri Elite.', 'E-Learning', '12:00', 0, array['core_av','core_net','core_doc']),
  ('KU-C-024', 'AVIXA', 'AV201', 'CTS 1: AV Technology', 'È un corso on-demand fondamentale per chi si prepara al CTS, dedicato alle basi della tecnologia AV. Copre i principi scientifici di suono, luce ed elettricità, i componenti dei sistemi audio e video, il ruolo del networking e dei sistemi di controllo, oltre ai fondamenti dell’industria AV e della gestione di progetto. È il primo modulo del percorso CTS Prep.', 'E-Learning', '24:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-025', 'AVIXA', 'AV201', 'CTS 2: Applied AV and AV Project Process', 'È un corso on-demand che prosegue il percorso CTS Prep dopo CTS 1, utile per approfondire le competenze chiave testate nell’esame CTS e applicarle in modo più concreto. Copre temi come business of AV, standard di settore, matematica applicata, raccolta requisiti, site survey, lettura dei disegni, principi di progettazione, project management, installazione, collaudo, manutenzione e troubleshooting.', 'E-Learning', '24:00', 0, array['adv_presales_av']),
  ('KU-C-026', 'AVIXA', 'NET101', 'AV for IT Pros', 'È un corso on-demand di circa 5 ore pensato per i professionisti IT che vogliono capire meglio la convergenza tra IT e AV, così da gestire e ottimizzare in modo più efficace i sistemi audiovisivi all’interno dell’infrastruttura di rete aziendale.', 'E-Learning', '05:00', 0, array['core_av','core_net']),
  ('KU-C-027', 'AVIXA', 'AV204', 'AV Math for Design Online', 'È un corso online on-demand dedicato alla matematica applicata alla progettazione AV, utile per rafforzare i calcoli usati nel design di sistemi audiovisivi, come distanze di visione, dimensioni immagine, proiezione, spaziatura dei diffusori, impedenza, wattaggio e aspetti infrastrutturali.', 'E-Learning', '15:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-028', 'AVIXA', 'AV204', 'AV Design 1: Environment Online', 'È un corso online on-demand dedicato alla progettazione dell’ambiente AV, utile per capire come tradurre i bisogni del cliente in un design concreto, considerando processo progettuale, ergonomia, principi visivi e principi audio. Include anche esercitazioni basate su scenari pratici e materiali AVIXA da usare nel lavoro.', 'E-Learning', '24:00', 0, array['adv_presales_av']),
  ('KU-C-029', 'AVIXA', 'AV204', 'AV Design 2: Infrastructure Online', 'È un corso online on-demand dedicato all’infrastruttura per la progettazione AV, utile per capire come il contesto edilizio influenzi il design dei sistemi audiovisivi, considerando impianti elettrici, acustica, illuminazione, HVAC, montaggio e coordinamento con le altre discipline tecniche. (avixa.org )', 'E-Learning', '24:00', 0, array['adv_presales_av']),
  ('KU-C-030', 'AVIXA', 'AV204', 'AV Design 3: Applied Design Online', 'È un corso online on-demand dedicato alla progettazione AV applicata, utile per sviluppare competenze pratiche su segnali audio/video digitali, EDID, processing audio, gain structure, reti AV, multicast, sicurezza dei sistemi e principi di human-centered design. (avixa.org )', 'E-Learning', '24:00', 0, array['adv_presales_av']),
  ('KU-C-031', 'AVIXA', 'AV204', 'Audiovisual Network Professional (ANP) Prep', 'È un corso online on-demand di preparazione all’esame ANP pensato per professionisti AV e IT che vogliono arrivare preparati alla certificazione Audiovisual Network Professional. Aiuta a ripassare i fondamenti di networking, le soluzioni AV in rete, le operazioni di sicurezza e troubleshooting, oltre a familiarizzare con struttura dell’esame, formato delle domande e strategie di test-taking. Attenzione: il corso non iscrive all’esame, che va richiesto e pagato separatamente.', 'E-Learning', '24:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-E-003', 'AVIXA', 'AV204', 'Audiovisual Network Professional Certification', 'È la certificazione AVIXA ANP (Audiovisual Network Professional), pensata per professionisti AV e IT che vogliono dimostrare competenze nell’integrazione dei sistemi AV in rete. Valida la capacità di collegare correttamente apparati AV al network, oppure, lato IT, di integrare correttamente l’AV nell’infrastruttura di rete. L’esame si sostiene solo in presenza presso centri Pearson VUE, ha una validità di 3 anni, non richiede il CTS e al momento è disponibile solo in inglese.', 'Certification', '02:30', 250, array['adv_presales_av']),
  ('KU-E-004', 'DANTE', 'AV101', 'Dante Certification Level 1', 'È un corso introduttivo gratuito pensato per iniziare con Dante e l’AV over IP, utile per capire i fondamenti di audio digitale, video e networking, con anche dimostrazioni pratiche su Dante Controller. L’obiettivo è fornire le basi per progettare e gestire reti Dante semplici a singolo switch, ed è indicato per professionisti AV, integratori e personale IT che si avvicinano al networking AV.', 'Certification', null, 0, array['core_av','core_net','core_doc']),
  ('KU-E-005', 'DANTE', 'AV101', 'Dante Certification Level 2', 'È un corso intermedio gratuito pensato per approfondire le competenze su networking Dante in ambienti AV più strutturati, con focus su reti gestite, prestazioni ottimizzate e troubleshooting professionale. Copre temi come IP networking, QoS, VLAN, IGMP, ridondanza e un uso più avanzato di Dante Controller, per progettare e gestire con sicurezza sistemi Dante in contesti aziendali.', 'Certification', null, 0, array['core_av','core_doc']),
  ('KU-E-006', 'DANTE', 'AV202', 'Dante Certification Level 3', 'È il livello più avanzato della certificazione Dante, pensato per professionisti AV e IT che gestiscono sistemi Dante su scala enterprise. Approfondisce temi come deployment su subnet multiple, sincronizzazione PTP, automazione tramite Dante API e progettazione di reti AV resilienti e sicure, con una visione adatta a infrastrutture complesse e distribuite.', 'Certification', null, 0, array['adv_presales_av','adv_eng_av','adv_doc']),
  ('KU-E-007', 'DANTE', 'AV202', 'Dante Domain Manager Administrator Certification', 'È una certificazione specialistica avanzata pensata per chi vuole approfondire la gestione di reti Dante oltre i livelli 1, 2 e 3, con focus su Dante Domain Manager. Il corso spiega come distribuire e configurare DDM, gestire segmentazione logica dei domini, clocking avanzato, utenti e logging, e comprendere come DDM interagisce con Dante Controller in reti più grandi e complesse.', 'Certification', null, 0, array['adv_eng_av','adv_doc']),
  ('KU-E-008', 'DANTE', 'AV301', 'Dante Mastery Certification', 'È una certificazione avanzata e a pagamento, pensata per professionisti AV e IT che vogliono distinguersi nella gestione di sistemi Dante complessi attraverso una formazione pratica, intensiva e in presenza. Si svolge in 4 giorni presso le sedi Audinate di Portland o Cambridge e approfondisce temi come configurazione degli switch, ottimizzazione della rete Dante, troubleshooting avanzato, reti Layer 3, Dante Domain Manager e Dante Director. È il livello più alto della formazione Dante.', 'Certification', '32:00', 2000, array['spec_eng_av']),
  ('KU-E-009', 'NDI', 'AV101', 'NDI Basics', 'È un corso introduttivo on-demand su NDI pensato per apprendere i fondamenti della tecnologia NDI e dell’AV over IP, utile per capire workflow, differenze rispetto a SDI, switching, discovery, registration e principali casi d’uso. Il percorso include 8 contenuti con assessment finale, richiede il superamento dei quiz per ottenere il badge.', 'Certification', null, 0, array['core_av','core_doc']),
  ('KU-E-010', 'NDI', 'AV203', 'NDI Professional', 'È un corso on-demand di livello avanzato su NDI, pensato per sviluppare competenze più tecniche nella progettazione, gestione e ottimizzazione di workflow NDI scalabili. Copre temi come discovery avanzata, reti multi-switch e multi-subnet, multicast, architettura NDI, troubleshooting con NDI Analysis e uso degli NDI Tools, e prevede un assessment finale da 30 domande con certificazione al superamento.', 'Certification', null, 25, array['adv_presales_av','adv_eng_av']),
  ('KU-E-011', 'NDI', 'AV101', 'NDI Tools', 'È un percorso on-demand dedicato agli NDI Tools, pensato per imparare in modo pratico a usare la suite gratuita di applicazioni NDI nei workflow AV e broadcast. Include 11 moduli brevi su strumenti come Access Manager, Audio Direct, Screen Capture, Webcam Input, Bridge, Router, Remote, Test Patterns, VLC Plugin, Adobe Plugins e Studio Monitor, con focus su routing, monitoraggio, contributi remoti, controllo, diagnostica e integrazione software.', 'Certification', null, 0, array['core_av','core_doc']),
  ('KU-C-032', 'KNX & DALI', null, 'Corso Base Ohmega Progettazioni', 'E'' un corso introdutti di KNX e DALI che permette ai tecnici di comprendere le caratteristiche di questi due bus di comunicazione e di poter gestire il coordinamenti con le figure deicate alla lora configurazione durante i cantieri. Prezzo a giornata con un numero n di studenti)', 'In-Class', '08:00', 700, array['adv_presales_av','adv_presales_net','adv_presales_sec']),
  ('KU-C-033', 'AVIGILON', 'SEC201', 'Avigilon Unity Video8', 'Technicians that are responsible for installing and maintaining an Avigilon Unity Video system.', 'E-Learning', '21:00', 0, array['adv_eng_sec']),
  ('KU-C-034', 'AVIGILON', 'SEC201', 'Avigilon Unity Video', 'Corso Sales e presales direttamente con Vendor in person con Presentazione prodotti e costruzione Progetti', 'In-Class', '08:00', 0, array['adv_eng_sec']),
  ('KU-C-035', 'AVIGILON', 'SEC201', 'Avigilon Alta Video (Ava/Aware) Configuration and Operation', 'This course is for installers and integrators seeking foundational knowledge in key functions of the Avigilon Alta Video (Ava/Aware) platform.', 'E-Learning', '04:00', 0, array['adv_eng_sec']),
  ('KU-C-036', 'AVIGILON', 'SEC101', 'Alta Video Pre sales e Sales', 'Corso Sales e presales direttamente con Vendor in person con Presentazione prodotti e costruzione Progetti', 'In-Class', '08:00', 0, array['core_sec','core_doc']),
  ('KU-C-037', 'AVIGILON', 'SEC201', 'Avigilon Alta Access Installation and Configuration', 'Corso OnlinePer installation e configuration del sistema', 'E-Learning', '05:00', 0, array['adv_eng_sec']),
  ('KU-C-038', 'AVIGILON', 'SEC101', 'Alta Access Pre sales e sales', 'Corso Sales e presales direttamente con Vendor in person con Presentazione prodotti e costruzione Progetti', 'In-Class', '08:00', 0, array['core_sec','core_doc']),
  ('KU-C-040', 'AXIS', 'SEC101', 'Get to know network technology', 'È un breve corso on-demand di taglio introduttivo dedicato ai fondamenti del networking, utile per comprendere i concetti base delle reti applicate al mondo video e AV. Copre temi come come i dati viaggiano in rete, capacità dei diversi tipi di cavo e principi del Power over Ethernet (PoE), insieme alle nozioni di base su componenti di rete e progettazione. Il corso dura circa 30–40 minuti, è gratuito e non richiede prerequisiti, con l’obiettivo di fornire una prima comprensione della tecnologia di rete e del video su IP.', 'E-Learning', '00:40', 0, array['core_sec']),
  ('KU-C-041', 'AXIS', 'SEC101', 'Get to know lighting for video surveillance', 'È un breve corso on-demand introduttivo dedicato all’illuminazione applicata alla videosorveglianza, utile per comprendere come la luce influenzi la qualità delle immagini video. Copre temi come importanza della luce, differenza tra illuminazione visibile e infrarossa (IR), condizioni di ripresa in ambienti bui e principi di progettazione dell’illuminazione, includendo anche consigli pratici per la site planning. Il corso dura circa 15 minuti ed è pensato per fornire una base su come ottenere immagini efficaci in diverse condizioni di luce.', 'E-Learning', '00:15', 0, array['core_sec']),
  ('KU-C-042', 'AXIS', 'SEC101', 'Get to know image quality optimization', 'È un breve corso on-demand introduttivo dedicato all’ottimizzazione della qualità dell’immagine nei sistemi video, utile per comprendere come ottenere riprese efficaci in diversi contesti. Copre fattori come risoluzione, sensori, frame rate, esposizione e velocità dell’otturatore, oltre al corretto posizionamento delle telecamere e alla gestione di condizioni complesse come aree molto luminose o in ombra. L’obiettivo è fornire le basi per configurare e installare sistemi video in modo da massimizzare la qualità delle immagini.', 'E-Learning', '00:15', 0, array['core_sec']),
  ('KU-C-043', 'AXIS', 'SEC101', 'Get to know Axis network camera product types', 'È un breve corso on-demand introduttivo dedicato ai diversi tipi di telecamere di rete Axis, utile per comprendere le differenze tra le varie soluzioni e quando utilizzarle nei diversi scenari di videosorveglianza. Copre le principali categorie come fixed dome, bullet, PTZ, panoramic, termiche e modulari, spiegandone caratteristiche, punti di forza e casi d’uso tipici. L’obiettivo è fornire una base per scegliere la tipologia di camera più adatta in funzione delle esigenze di sicurezza e del contesto applicativo.', 'E-Learning', '00:15', 0, array['core_sec']),
  ('KU-C-044', 'AXIS', 'SEC101', 'Get to know Axis network camera naming convention', 'È un breve corso on-demand introduttivo dedicato alla nomenclatura delle telecamere di rete Axis, utile per capire come leggere e interpretare correttamente i codici prodotto. Spiega come il nome di una camera riveli in modo standardizzato informazioni come linea, tipo, serie, risoluzione, numerazione ed eventuali estensioni/funzionalità, con l’obiettivo di permettere di confrontare e selezionare i prodotti direttamente dal codice; il corso dura circa 20–30 minuti, è gratuito e non richiede prerequisiti.', 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-045', 'AXIS', 'SEC101', 'Funzionalità di ricerca forense in AXIS Optimizer for Milestone Xprotect', null, 'E-Learning', '00:20', 0, array['core_sec']),
  ('KU-C-046', 'AXIS', 'SEC101', 'Scopri AXIS License Manager', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-047', 'AXIS', 'SEC101', 'Scopri AXIS License Plate Verifier', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-048', 'AXIS', 'SEC101', 'Informazioni su AXIS Perimeter Defender', null, 'E-Learning', '00:20', 0, array['core_sec']),
  ('KU-C-049', 'AXIS', 'SEC101', 'Get to know Axis thermal and thermometric cameras', null, 'E-Learning', '00:20', 0, array['core_sec']),
  ('KU-C-050', 'AXIS', 'SEC101', 'Scopri la sicurezza informatica in Axis', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-051', 'AXIS', 'SEC101', 'Telecamere protette contro le esplosioni', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-052', 'AXIS', 'SEC101', 'Qualità di immagine applicata', null, 'E-Learning', '00:15', 0, array['core_sec']),
  ('KU-C-053', 'AXIS', 'SEC101', 'Guardati intorno con le telecamere panoramiche', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-054', 'AXIS', 'SEC101', 'Soluzioni per la sicurezza perimetrale e dell''area', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-055', 'AXIS', 'SEC101', 'Introduzione ai radar di sicurezza', null, 'E-Learning', '00:45', 0, array['core_sec']),
  ('KU-C-056', 'AXIS', 'SEC101', 'Sfruttare al massimo l''analisi video', null, 'E-Learning', '00:30', 0, array['core_sec']),
  ('KU-C-057', 'AXIS', 'SEC201', 'A&E - Progettazione delle soluzioni video di rete', null, 'In-Class', '08:00', 0, array['adv_presales_sec','adv_eng_sec']),
  ('KU-C-058', 'AXIS', 'SEC201', 'Analitiche Video Avanzate', null, 'In-Class', '08:00', 0, array['adv_eng_sec']),
  ('KU-C-059', 'AXIS', 'SEC201', 'AXIS Perimeter Defender', null, 'In-Class', '08:00', 0, array['adv_presales_sec','adv_eng_sec']),
  ('KU-C-060', 'AXIS', 'SEC201', 'Intrusion Protection Avanzata', null, 'In-Class', '08:00', 0, array['adv_eng_sec']),
  ('KU-C-061', 'BARCO', 'AV102', 'Assessment', null, 'E-Learning', '01:00', 0, array['core_av','core_doc']),
  ('KU-C-062', 'BARCO CTRL', 'AV203', 'Barco CTRL Continued Education', 'È un corso di aggiornamento professionale su Barco CTRL pensato per chi vuole consolidare e mantenere aggiornate le competenze sulla piattaforma KVM over IP per control room di Barco. Si inserisce nel percorso di training & certification del prodotto ed è utile per approfondire uso, supporto e gestione operativa dell’ecosistema Barco CTRL in contesti di sala controllo.', 'E-Learning', '01:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-063', 'BARCO CTRL', 'AV203', 'Barco CTRL Sales Specialist', 'È un corso introduttivo su Barco CTRL pensato per fornire una panoramica iniziale della piattaforma KVM over IP per control room di Barco. Serve a capire cos’è Barco CTRL, come si posiziona in sala controllo e quali sono i suoi pilastri principali — semplicità, scalabilità e sicurezza — così da creare una base utile prima dei moduli più operativi o specialistici.', 'E-Learning', '00:20', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-064', 'BARCO CTRL', 'AV203', 'Barco CTRL Technical Associate', 'È un corso tecnico su Barco CTRL pensato per chi vuole sviluppare competenze operative sulla piattaforma KVM over IP per control room, con un taglio più pratico rispetto al modulo introduttivo. Si inserisce nel percorso di training e certificazione Barco per tecnici e specialisti, orientato a temi come installazione, configurazione, riconfigurazione e troubleshooting di base dei sistemi.', 'E-Learning', '01:30', 0, array['adv_eng_av']),
  ('KU-E-012', 'BARCO CTRL', 'AV306', 'Barco CTRL Technical Expert', 'È un corso/certificazione tecnica avanzata su Barco CTRL pensato per professionisti che vogliono sviluppare una competenza più approfondita sulla piattaforma KVM over IP per control room. Si colloca nel livello Expert del percorso Barco, quindi con focus su configurazione avanzata, manutenzione, troubleshooting approfondito, analisi dei log ed escalation verso R&D, applicati all’ecosistema Barco CTRL.', 'Certification', '16:00', 1400, array['spec_eng_av']),
  ('KU-E-013', 'BARCO CTRL', 'AV306', 'Barco UniSee', 'È un corso/certificazione tecnica avanzata su Barco UniSee pensato per professionisti che vogliono sviluppare competenze approfondite sui videowall LCD bezel-less di Barco in contesti professionali. Si colloca nel livello Expert del percorso Barco, quindi con focus su installazione e riconfigurazione avanzata, manutenzione, troubleshooting approfondito, raccolta e analisi dei log ed escalation verso R&D applicati all’ecosistema UniSee.', 'Certification', '16:00', 1400, array['spec_eng_av']),
  ('KU-C-065', 'BARCO VIDEO', 'AV102', 'Technical Introduction', 'È un corso e-learning introduttivo tecnico su Barco Event Master, pensato per fornire una panoramica delle specifiche tecniche dei diversi sistemi Event Master e dei relativi card set. Serve a creare una base iniziale utile per comprendere meglio l’architettura della piattaforma di image processing Barco nei contesti live e professionali.', 'E-Learning', '01:00', 0, array['core_av','core_doc']),
  ('KU-E-014', 'BARCO VIDEO', 'AV202', 'E2 Gen2', 'È un corso/certificazione specialistica in aula su Barco Event Master, pensato per tecnici AV, technical director e pre-sales che devono configurare, usare e comprendere in profondità la piattaforma nei live event. Copre hardware Event Master, terminologia video digitale, setup e operation, Toolset, controller EC-30/EC-50, linking con Ex, applicazioni widescreen/multi-screen/LED wall e include esami pratici e teorici per ottenere la qualifica Barco Certified Specialist, valida 2 anni.', 'Certification', '32:00', 2000, array['adv_eng_av']),
  ('KU-E-015', 'BARCO VIDEO', 'AV307', 'E2 Gen2 (Level 2)', 'È un corso avanzato in aula su Barco Event Master E2 Gen2 (Level 2), pensato per chi vuole sviluppare competenze più approfondite sulla piattaforma di image processing per eventi live. Si colloca nel livello Expert del percorso Barco, con focus su configurazione avanzata, gestione operativa e troubleshooting dei sistemi Event Master in contesti professionali.', 'Certification', '24:00', 2400, array['spec_eng_av']),
  ('KU-E-016', 'BARCO VIDEO', 'AV307', 'Event Master Encore3 Certified Specialist', 'È un corso specialistico completo su Barco Encore3 / Event Master, pensato sia per chi conosce già Event Master E2 sia per chi è nuovo nel mondo Barco Image Processing. Fornisce una formazione approfondita sul prodotto attuale Encore3 e, al completamento del percorso di 3 giorni, porta alla certificazione Level 1 Specialist. Il link russo che hai inviato non risulta disponibile, ma il contenuto corrisponde alla pagina Barco del corso Event Master Encore3 Technical Specialist Full / Certified Specialist.', 'Certification', '24:00', 1400, array['spec_eng_av']),
  ('KU-E-017', 'BARCO VIDEO', 'AV203', 'Corso Image Processor presso Comm-Tec', 'Corso organizzato da comm-tec che garantisce una formazione generale sui processori grafici e la loro configurazione.', 'Certification', null, 0, array['adv_eng_av','adv_doc']),
  ('KU-C-066', 'BRIGHTSIGN', 'AV203', 'brightAuthor connected 101', 'Corso base e generico sull''utilizzo dei brightsign.', 'E-Learning', '04:00', 0, array['adv_eng_av','adv_doc']),
  ('KU-C-067', 'CISCO', 'KAPLET101', 'Black Belt New Hire', null, 'E-Learning', null, 0, array['core_av','core_net','core_sec','core_doc']),
  ('KU-C-068', 'CISCO', 'KAPLET101', 'Black Belt (Collaboration) almeno 25 in totale', null, 'E-Learning', null, 0, array['core_av','core_net','core_sec','core_doc']),
  ('KU-C-069', 'CISCO', 'KAPLET101', 'Black Belt (Networking) almeno 25 in totale', null, 'E-Learning', null, 0, array['core_av','core_net','core_sec','core_doc']),
  ('KU-E-018', 'CISCO', 'NET101', 'Cisco Certified Support Technician (CCST) Networking', 'È la certificazione CCST IT Support, pensata per validare competenze entry-level di supporto IT e preparare a ruoli come help desk, end-user support, computer support specialist e IT help desk analyst. Fa parte del percorso Cisco Certified Support Technician e, per ottenerla, bisogna superare un esame core; Cisco indica che non ci sono prerequisiti formali.', 'Certification', null, 125, array['core_net','core_doc']),
  ('KU-E-019', 'CISCO', 'NET101', 'Certified Support Technician (CCST) IT Support', 'È la famiglia di certificazioni Cisco Certified Support Technician (CCST), pensata per ruoli entry-level IT. Valida competenze di base in networking, cybersecurity o IT support, non richiede prerequisiti formali e si ottiene superando un esame core per ciascun percorso. Cisco la presenta anche come primo passo verso certificazioni associate come CCNA o Cisco Certified Cybersecurity Associate.', 'Certification', null, 125, array['core_av','core_net','core_sec','core_doc']),
  ('KU-E-020', 'CISCO', 'NET101', 'Cisco Certified Network Associate (CCNA)', 'È la certificazione Cisco CCNA (Cisco Certified Network Associate), pensata per validare competenze fondamentali in networking, IP connectivity, IP services, security e automazione. È un titolo molto riconosciuto per chi vuole iniziare o consolidare una carriera in ambito reti e IT. Per ottenerla bisogna superare un unico esame, non ci sono prerequisiti formali, anche se Cisco segnala che può essere utile avere 1 o più anni di esperienza pratica con soluzioni Cisco. La certificazione ha validità 3 anni.', 'Certification', null, 300, array['core_net']),
  ('KU-E-021', 'CISCO', 'AV205', 'Cisco Certified Network Professional Collaboration', 'È la certificazione Cisco CCNP Collaboration, pensata per professionisti che vogliono validare competenze avanzate nelle tecnologie di collaborazione, tra cui infrastruttura e design, protocolli, endpoint, applicazioni collaboration e call control. Per ottenerla bisogna superare 2 esami: 1 core exam e 1 concentration exam; non ci sono prerequisiti formali, anche se Cisco indica spesso 3–5 anni di esperienza nel settore. La certificazione ha validità 3 anni.', 'Certification', null, 400, array['adv_eng_av']),
  ('KU-E-022', 'CISCO', 'NET201', 'Cisco Certified Network Professional Enterprise', 'È la certificazione Cisco CCNP Enterprise, pensata per professionisti che vogliono validare competenze avanzate nelle reti enterprise, inclusi infrastructure, virtualization, network assurance, security e automation. Per ottenerla bisogna superare 2 esami: 1 core exam e 1 concentration exam; non ci sono prerequisiti formali, anche se Cisco indica spesso 3–5 anni di esperienza nell’implementazione di soluzioni enterprise. La certificazione ha validità 3 anni.', 'Certification', null, 400, array['adv_eng_net']),
  ('KU-E-023', 'CISCO', 'NET202', 'Cisco Certified Network Professional Wireless', 'È la nuova certificazione Cisco CCNP Wireless, che Cisco introdurrà dal 19 marzo 2026 per riportare in un percorso dedicato le competenze wireless prima incluse nel CCNP Enterprise. È pensata per professionisti che vogliono validare competenze avanzate su reti Wi-Fi enterprise, progettazione, implementazione, troubleshooting e tecnologie moderne come Wi-Fi 6, Wi-Fi 7 e Cisco Meraki.', 'Certification', null, 400, array['adv_eng_net']),
  ('KU-E-024', 'CISCO', 'AV305', 'Cisco Certified Internetwork Expert (CCIE) Collaboration', 'È la certificazione Cisco CCIE Collaboration, pensata per professionisti senior che vogliono validare competenze di livello expert nella progettazione, implementazione, operation e ottimizzazione di soluzioni di collaboration complesse. Copre aree come unified communications, gestione e analytics cloud-connected, hybrid/cloud calling, Webex Contact Center e API. Per ottenerla bisogna superare 2 esami: 1 core exam e 1 practical exam; non ci sono prerequisiti formali, anche se Cisco raccomanda 5–7 anni di esperienza. La certificazione ha validità 3 anni.', 'Certification', null, 400, array['spec_eng_av']),
  ('KU-E-025', 'CISCO', 'NET301', 'Cisco Certified Internetwork Expert (CCIE) Enterprise', 'È la certificazione Cisco CCIE Enterprise Infrastructure, pensata per professionisti senior che vogliono validare competenze di livello expert nelle reti enterprise, dalla progettazione e implementazione fino a operation, ottimizzazione, sicurezza, servizi e automazione. Per ottenerla bisogna superare 2 esami: 1 core exam scritto e 1 lab pratico hands-on; non ci sono prerequisiti formali, anche se Cisco raccomanda 5–7 anni di esperienza. La certificazione ha validità 3 anni.', 'Certification', null, 400, array['spec_eng_net']),
  ('KU-E-026', 'CISCO', 'NET302', 'Cisco Certified Internetwork Expert (CCIE) Enterprise Wireless', 'È la certificazione Cisco CCIE Enterprise Wireless, pensata per professionisti senior che vogliono validare competenze di livello expert nella progettazione, implementazione, operation e ottimizzazione di reti wireless enterprise complesse. Copre aree come architetture wireless, sicurezza, analytics, automazione e programmabilità. Per ottenerla bisogna superare 2 esami: 1 core exam e 1 lab pratico hands-on; non ci sono prerequisiti formali, anche se Cisco raccomanda 5–7 anni di esperienza. La certificazione ha validità 3 anni.', 'Certification', null, 400, array['spec_eng_net']),
  ('KU-C-070', 'CRESTRON', 'AV102', 'Crestron Basics - Commercial', 'È un learning path introduttivo per il mercato commerciale pensato per fornire le competenze essenziali per progettare e installare soluzioni Crestron enterprise-grade. Copre una panoramica dei prodotti Crestron con focus su conferencing e collaboration, video intelligente, distribuzione AV avanzata, networking AV, AV over IP, XiO Cloud, sicurezza e USB, costruendo una base tecnica utile per chi inizia a lavorare con l’ecosistema Crestron.', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-071', 'CRESTRON', 'AV102', 'Crestron Commercial Solutions (No Classroom)', 'È un learning path dedicato alle soluzioni Crestron per ambienti commerciali, pensato per sviluppare competenze su progettazione, implementazione e gestione di sistemi AV professionali in contesti corporate. Copre temi come DigitalMedia, room scheduling, sistemi di controllo, AV Framework, switch USB, applicazioni commerciali e design degli spazi, con l’obiettivo di migliorare collaborazione, uniformità d’esperienza e produttività negli ambienti di lavoro.', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-072', 'CRESTRON', 'AV102', 'Crestron Certified Technology Architect - Commercial (CTA-C)', 'È un percorso di certificazione avanzato per il mercato commerciale, pensato per AV designer, tecnici e figure technical sales che vogliono approfondire le tecnologie Crestron più evolute. Copre Crestron Basics, software e strumenti, DM NVX, intelligent video e Automate VX, Flex conferencing & collaboration, lighting & shades, soluzioni commerciali e XiO Cloud, con un approccio orientato a progettazione, implementazione e gestione di sistemi AV avanzati; al termine consente di ottenere la certificazione Crestron Certified Technology Architect – Commercial (CTA-C).', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-073', 'CRESTRON', 'AV102', 'DM NVX® Technology - Certified Designer', 'È un percorso di certificazione specialistico dedicato alla progettazione di sistemi AVoIP con tecnologie Crestron, pensato per chi vuole approfondire DM NVX, DM NAX e DM NUX. Copre design di soluzioni AV over IP, risorse progettuali, scenari applicativi, utilizzo del PoE, sicurezza di rete, terminologia IT, DM NVX Director e XiO Cloud, con un approccio orientato a progettazione e implementazione di ecosistemi AV su rete; al termine permette di sviluppare competenze avanzate come Certified Designer nell’ambito DM NVX Technology.', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-074', 'CRESTRON', 'AV203', 'DM NVX® Technology - Certified Engineer', 'È un percorso di certificazione tecnico-pratico dedicato alla tecnologia DM NVX AV-over-IP, pensato per chi vuole acquisire esperienza concreta nella progettazione, configurazione, deployment e troubleshooting di soluzioni Crestron su rete. Copre l’integrazione di video, audio e USB in ambiente IP, con un approccio orientato all’intero ciclo di vita del sistema, dal concept fino alla messa in esercizio; al termine consente di sviluppare competenze operative avanzate come Certified Engineer nell’ambito DM NVX Technology.', 'E-Learning', null, 0, array['adv_eng_av']),
  ('KU-C-075', 'CRESTRON', 'AV310', 'Intelligent Video - Certified Designer', 'È un percorso di certificazione specialistico dedicato alla progettazione di soluzioni Crestron Intelligent Video con Automate VX, pensato per chi vuole imparare a disegnare e implementare correttamente sistemi di tracking e regia automatica in ambienti diversi. Copre posizionamento di camere e microfoni, criteri progettuali per le varie tipologie di spazio, uso del tool Automate VX Room Designer e generazione del file di progetto per design review e deployment, con un approccio orientato a progettazione accurata e implementazione efficace; al termine consente di ottenere la certificazione Intelligent Video Certified Design (IVC-D).', 'E-Learning', null, 0, array['spec_eng_av']),
  ('KU-C-076', 'CRESTRON', 'AV310', 'Intelligent Video - Certified Engineer', 'È un percorso di certificazione tecnico-pratico dedicato alle soluzioni Crestron Intelligent Video con Automate VX, pensato per chi vuole imparare a configurare, mettere in servizio e risolvere problemi in ambienti meeting ad alto impatto come boardroom e lecture hall. Copre commissioning, troubleshooting, ottimizzazione delle inquadrature, tracciamento del relatore attivo, layout video personalizzati, registrazione e streaming integrati, oltre all’integrazione con piattaforme di videoconferenza esistenti, con un approccio orientato a gestione operativa e implementazione avanzata; al termine consente di ottenere la certificazione Intelligent Video Certified Engineer (IVC-E).', 'E-Learning', null, 0, array['spec_eng_av']),
  ('KU-C-077', 'CRESTRON', 'AV102', 'Technician, Crestron Commercial - Certification', 'È un percorso di certificazione per tecnici AV in ambito commerciale, pensato per chi vuole acquisire le basi per installare, configurare e mettere in servizio soluzioni Crestron complesse. Copre commissioning di sistemi completi, integrazione con apparati di terze parti, terminologia di settore, configurazione dei dispositivi Crestron, uso dei software applicativi e supporto post-installazione, con un approccio orientato a attività operative e avviamento dei sistemi; al termine consente di ottenere la certificazione Technician, Crestron Commercial.', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-140', 'CRESTRON', null, 'Crestron Core Track', null, 'E-Learning', null, null, '{}'),
  ('KU-C-141', 'CRESTRON', null, 'Crestron Fundamentals Commercial (CTI-CFC)', null, 'E-Learning', null, null, '{}'),
  ('KU-C-142', 'CRESTRON', null, 'Crestron Network Solutions - Introduzione (CNS-I)', null, 'E-Learning', null, null, '{}'),
  ('KU-C-143', 'CRESTRON', null, 'Crestron Network Solutions - Design (CNS-D)', null, 'E-Learning', null, null, '{}'),
  ('KU-C-144', 'CRESTRON', null, 'DigitalMedia 4K Designer', null, 'E-Learning', null, null, '{}'),
  ('KU-C-078', 'ELMO', 'SEC202', 'Elmo Security', 'E'' Un percorso formativo Tecnico/Pre sales con presentazione prodotti e corso Base /Avanzato di configurazione apparati', 'In-Class', '08:00', 0, array['adv_eng_sec','adv_doc','adv_field']),
  ('KU-C-079', 'EXTRON', 'AV101', 'AV Associate', 'È un programma di certificazione online introduttivo pensato per fornire una solida base sulle tecnologie AV fondamentali e una panoramica dei prodotti e delle applicazioni Extron. Copre temi come networking, controllo di sistema ed elaborazione digitale del segnale, si segue online in autonomia da desktop o mobile e rappresenta anche la base per i percorsi di certificazione avanzati Extron.', 'E-Learning', '27:00', 0, array['core_av','core_doc']),
  ('KU-C-080', 'EXTRON', 'AV202', 'ProDSP Specialist', 'È un programma di certificazione online specialistico pensato per chi vuole approfondire la configurazione, il controllo e l’ottimizzazione di sistemi audio con prodotti Extron ProDSP. Copre l’uso del software DSP Configurator, i criteri di setup e tuning audio, l’impiego di template e blocchi di elaborazione, la validazione delle configurazioni DSP in diverse applicazioni AV, oltre a temi come Dante e VoIP in ambito audio di rete; è indicato per professionisti che installano, configurano e ottimizzano sistemi audio AV.', 'E-Learning', null, 0, array['adv_eng_av']),
  ('KU-C-081', 'EXTRON', 'AV201', 'NetworkAV Specialist', 'È un programma di certificazione online specialistico pensato per chi vuole approfondire la progettazione, il deployment, il commissioning e il troubleshooting di sistemi AV over IP con ecosistema Extron NAV. Copre configurazioni punto-punto e multipunto, best practice d’uso di NAVigator per gestione e controllo sicuri, pianificazione del sistema, sicurezza di rete e workflow operativi, con un approccio orientato a implementazione e gestione di sistemi AV in rete; al termine sviluppa competenze come Network AV Specialist (NAVS).', 'In-Class', null, 0, array['adv_presales_av','adv_eng_av','adv_doc']),
  ('KU-E-027', 'FORTINET', 'NET101', 'NSE 1+2 | Fortinet Certified Fundamentals Cybersecurity', 'È un percorso formativo introduttivo sulla cybersecurity (Fortinet Certified Fundamentals), pensato per fornire una base solida sui concetti fondamentali della sicurezza informatica. Copre il panorama delle minacce, i principi di sicurezza, le tecniche di protezione e le principali tecnologie, con l’obiettivo di preparare a ruoli entry-level o a chi necessita di una comprensione generale della cybersecurity.', 'Certification', null, 0, array['core_sec','core_doc']),
  ('KU-E-028', 'FORTINET', 'NET203', 'NSE 3 | Fortinet Certified Professional Security Operations', 'È un percorso formativo di livello base-intermedio sulla cybersecurity (Fortinet Certified Associate – FCA), pensato per sviluppare competenze operative nella gestione e configurazione dei dispositivi di sicurezza FortiGate.

Il corso copre le funzionalità principali dei firewall Fortinet, incluse attività come configurazione di rete, policy di sicurezza, VPN, controllo accessi, monitoraggio e protezione dalle minacce, con l’obiettivo di fornire una comprensione pratica delle operazioni di sicurezza più comuni. 

È rivolto a professionisti IT e cybersecurity che devono gestire o amministrare infrastrutture di sicurezza, e richiede il superamento di un esame finale (FortiGate Operator) per ottenere la certificazione, valida tipicamente per due anni.', 'Certification', '06:30', 0, array['adv_eng_sec']),
  ('KU-E-029', 'FORTINET', 'NET203', 'NSE 4+5 | Fortinet Certified Professional Security Operations', 'È un percorso formativo di livello intermedio sulla sicurezza operativa, pensato per sviluppare competenze nella gestione, monitoraggio e risposta agli incidenti di cybersecurity. Copre attività come analisi dei log, rilevamento delle minacce e gestione delle operazioni di sicurezza, con l’obiettivo di preparare ruoli operativi in ambito SOC e sicurezza IT.', 'Certification', null, 0, array['adv_eng_sec']),
  ('KU-E-030', 'FORTINET', 'NET203', 'NSE 4+5 | Fortinet Certified Professional Cloud Security Security Operations', 'È un percorso formativo di livello intermedio dedicato alla sicurezza in ambienti cloud, pensato per sviluppare competenze nella protezione di infrastrutture e applicazioni cloud. Copre temi come configurazione della sicurezza, gestione degli accessi, monitoraggio e protezione delle workload, con l’obiettivo di preparare a ruoli operativi nella cloud security.', 'Certification', null, 0, array['adv_eng_sec']),
  ('KU-E-031', 'FORTINET', 'NET203', 'NSE 4+5 | Fortinet Certified Professional SASE Security Operations', 'È un percorso formativo di livello intermedio dedicato all’architettura SASE (Secure Access Service Edge), pensato per sviluppare competenze nella protezione degli accessi a Internet, cloud e applicazioni SaaS. Copre la progettazione, implementazione e gestione di infrastrutture SASE, includendo concetti come accesso sicuro, Zero Trust e sicurezza cloud-based, con l’obiettivo di preparare ruoli tecnici nella network e cloud security.', 'Certification', null, 0, array['adv_eng_sec']),
  ('KU-E-032', 'FORTINET', 'NET203', 'NSE 4+5 | Fortinet Certified Professional Security Operations', 'È un percorso formativo di livello intermedio dedicato alla sicurezza delle reti, pensato per sviluppare competenze nella configurazione, gestione e monitoraggio di infrastrutture di network security. Copre attività operative come deployment di firewall, gestione delle policy, analisi del traffico e protezione delle applicazioni, con l’obiettivo di preparare ruoli tecnici nella network security e amministrazione di sistemi di sicurezza.', 'Certification', null, 0, array['adv_eng_sec']),
  ('KU-E-033', 'FORTINET', 'NET303', 'NSE 6+7 | Fortinet Certified Specialist Security Operations', 'È un percorso formativo avanzato dedicato alla security operations, pensato per sviluppare competenze nella progettazione, gestione e ottimizzazione di infrastrutture SOC. Copre attività come monitoraggio avanzato, analisi e risposta agli incidenti, troubleshooting e automazione delle operazioni di sicurezza, con l’obiettivo di preparare profili senior nella cybersecurity operativa e architettura di sicurezza.', 'Certification', null, 0, array['spec_eng_sec']),
  ('KU-E-034', 'FORTINET', 'NET303', 'NSE 6+7 | Fortinet Certified Specialist Cloud Security Security Operations', 'È un percorso formativo avanzato dedicato alla sicurezza in ambienti cloud, pensato per sviluppare competenze nella progettazione, gestione e ottimizzazione di architetture di cloud security a livello enterprise. Copre attività come design, amministrazione, monitoraggio e troubleshooting di soluzioni di sicurezza per applicazioni cloud pubbliche e private, con l’obiettivo di preparare profili senior nella cloud security e architettura di sicurezza avanzata.', 'Certification', null, 0, array['spec_eng_sec']),
  ('KU-E-035', 'FORTINET', 'NET303', 'NSE 6+7 | Fortinet Certified Specialist SASE Security Operations', 'È un percorso formativo avanzato dedicato all’architettura SASE (Secure Access Service Edge), pensato per sviluppare competenze nella progettazione, gestione e ottimizzazione di infrastrutture di accesso sicuro distribuite. Copre attività come design, deployment, monitoraggio e troubleshooting di soluzioni SASE, includendo componenti come SD-WAN, Zero Trust, secure web gateway e firewall-as-a-service, con l’obiettivo di preparare profili senior nella network e cloud security avanzata', 'Certification', null, 0, array['spec_eng_sec']),
  ('KU-E-036', 'FORTINET', 'NET303', 'NSE 6+7 | Fortinet Certified Specialist Security Operations', 'È un percorso formativo avanzato dedicato alla sicurezza delle reti, pensato per sviluppare competenze nella progettazione, gestione e ottimizzazione di infrastrutture di network security a livello enterprise. Copre attività come design, amministrazione, monitoraggio e troubleshooting di soluzioni avanzate (firewall, SD-WAN, routing e sicurezza integrata), con l’obiettivo di preparare profili senior nella network security e architettura di sicurezza', 'Certification', null, 0, array['spec_eng_sec']),
  ('KU-C-082', 'K-ARRAY', 'AV202', '2-DAY K-EXPERIENCE AT K-ARRAY HQ', null, 'In-Class', '16:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-083', 'K-ARRAY', 'AV202', 'K-ARRAY Certified Designer', null, 'E-Learning', '24:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-084', 'K-ARRAY', 'AV202', 'K-ARRAY Certified Installer', null, 'E-Learning', '24:00', 0, array['adv_eng_av']),
  ('KU-C-085', 'K-SCAPE', 'AV202', 'KSCAPE WEBINAR SERIES: RAIL S', null, 'E-Learning', '01:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-086', 'K-SCAPE', 'AV202', 'KSCAPE APPLICATION WEBINAR SERIES: CORPORATE', null, 'E-Learning', '01:00', 0, array['adv_presales_av']),
  ('KU-C-087', 'K-SCAPE', 'AV202', 'KSCAPE APPLICATION WEBINAR SERIES: HOSPITALITY', null, 'E-Learning', '01:00', 0, array['adv_presales_av']),
  ('KU-C-088', 'KSENIA', 'SEC202', 'Ksenia security', 'E'' Un percorso formativo Tecnico/Pre sales con presentazione prodotti e corso Base /Avanzato di configurazione apparati', 'In-Class', '16:00', 0, array['adv_eng_sec','adv_doc','adv_field']),
  ('KU-C-089', 'MAXHUB', 'AV102', 'MAXHUB XBoard V7 Series', null, 'E-Learning', '01:00', 0, array['core_av','core_doc']),
  ('KU-C-090', 'MILESTONE', 'SEC201', 'XProtect Certified Design Engineer (XCDE)', 'Gli ingegneri di progettazione XProtect progettano soluzioni di sorveglianza per soddisfare le esigenze dei clienti. La valutazione XProtect Certified Design Engineer (XCDE) verifica le tue conoscenze su: Nozioni di base sulla sorveglianza tecnica e video, progettazione del sondaggio del sito, architettura del sistema XProtect, prodotti ed estensioni XProtect, funzionalità di progettazione XProtect, workstation client intelligenti, licenze e assistenza XProtect, best practice per la sicurezza e la sicurezza informatica e gli strumenti e le risorse dei partner XProtect.', 'E-Learning', '16:00', 850, array['adv_presales_sec','adv_eng_sec']),
  ('KU-C-091', 'MILESTONE', 'SEC301', 'XProtect Certified Integration Technician (XCIT)', 'I tecnici di integrazione XProtect installano e configurano installazioni XProtect VMS moderatamente complesse con conteggi delle telecamere di 100-500 telecamere. La valutazione XProtect Certified Integration Technician (MCIT) verifica la tua capacità di eseguire questa attività.', 'E-Learning', '24:00', 1000, array['spec_eng_sec']),
  ('KU-C-092', 'MILESTONE', 'SEC301', 'XProtect Certified Integration Engineer (XCIE)', 'Gli ingegneri di integrazione certificati XProtect installano e configurano complesse installazioni XProtect con un conteggio delle telecamere di circa 100-10.000 telecamere. La valutazione XProtect Certified Integration Engineer (XCIE) verifica la tua conoscenza e capacità di eseguire attività relative a: Best Practice IT e sicurezza, Preparazione della distribuzione XProtect, Installazione XProtect, Impostazioni di configurazione XProtect, Comportamenti di configurazione XProtect, Espansione XProtect, Consegna XProtect e Manutenzione XProtect.', 'E-Learning', '24:00', 1500, array['spec_eng_sec']),
  ('KU-C-093', 'NOTIFIER', 'SEC101', 'Pre-Sales', 'Corso Pre Sales e Sales direttamente dal Distributore', 'In-Class', '08:00', 0, array['core_sec','core_doc']),
  ('KU-C-094', 'NOTIFIER', 'SEC203', 'Security Fire', 'Corso Tecnico Formativo che abilita alla Programmazione base Centrale Notifier', 'In-Class', '08:00', 0, array['adv_doc','adv_field']),
  ('KU-C-095', 'NOTIFIER', 'SEC203', 'Security Fire', 'Corso Tecnico Formativo che abilita alla Programmazione Avanzata Centrale Notifier', 'In-Class', '08:00', 0, array['adv_field']),
  ('KU-C-096', 'NOVASTAR', 'AV102', 'LED Screen Technician', 'È una certificazione introduttiva di livello base del programma Novastar Certified Engineer (NCE), pensata per formare tecnici junior sulle operazioni fondamentali e sulla manutenzione dei LED display. Copre terminologia di settore, architettura dei sistemi LED, componenti hardware, collegamenti, file di configurazione, software di base, tipologie di schermi, interfacce e scenari applicativi, con l’obiettivo di rendere il candidato capace di orientarsi rapidamente nel contesto tecnico dei display LED; è il livello foundation del percorso NCE e costituisce il prerequisito per le certificazioni successive.', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-097', 'NOVASTAR', 'AV311', 'Professional in LED Screen Solution Design', 'È una certificazione di livello intermedio del programma Novastar Certified Engineer (NCE), pensata per chi vuole sviluppare competenze nella progettazione di soluzioni per LED screen. È rivolta a professionisti che hanno già ottenuto la certificazione L1, come sales, pre-sales, solution designer e tecnici che vogliono evolvere verso attività di configurazione e design. Copre architetture avanzate di controllo LED, calcolo dei moduli e dei carichi, scelta dei prodotti Novastar, progettazione di topologie di sistema e sviluppo di soluzioni per piccoli e medi progetti LED; richiede NCE L1 e almeno un anno di esperienza nel settore LED.', 'In-Class', null, 0, array['core_av','core_doc','spec_eng_av']),
  ('KU-C-098', 'NOVASTAR', 'AV311', 'Specialist in LED Screen Solution Design', 'È una certificazione avanzata del programma Novastar Certified Engineer (NCE), pensata per formare professionisti capaci di progettare soluzioni complesse di LED display e sistemi di controllo. È rivolta soprattutto a pre-sales engineer, solution designer e figure tecniche con esperienza nel settore, e copre configurazioni multi-sending card, sincronizzazione, integrazione tra LED/LCD/proiezione, selezione della gamma prodotti Novastar e progettazione per scenari complessi come maxi-schermi, forme irregolari, bassa latenza, alta qualità d’immagine, trasmissione a lunga distanza, cluster publishing, 3D e soluzioni 5G; è indicata in particolare per chi ha già una base NCE L2 o almeno tre anni di esperienza nel settore LED.', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-099', 'NOVASTAR', 'AV311', 'Expert in LED Screen Solution Design', 'COMING SOON', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-100', 'NOVASTAR', 'AV311', 'Professional in LED Screen Implementation', 'È una certificazione di livello intermedio del programma Novastar Certified Engineer (NCE), pensata per formare tecnici con competenze pratiche nell’installazione, configurazione e manutenzione di LED display. È rivolta soprattutto a tecnici, post-sales engineer e rental engineer che hanno già ottenuto la certificazione L1, e copre architetture di controllo avanzate, uso dei principali prodotti Novastar, operazioni avanzate in NovaLCT e troubleshooting completo della catena di sistema; al termine consente di gestire in autonomia installazione, debug e manutenzione di base di progetti LED di piccole e medie dimensioni.', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-101', 'NOVASTAR', 'AV311', 'Specialist in LED Screen Implementation', 'È una certificazione avanzata del programma Novastar Certified Engineer (NCE), pensata per formare figure senior specializzate nell’implementazione di sistemi di controllo per LED display complessi. È rivolta soprattutto a technical support engineer, after-sales engineer, rental engineer e professionisti con oltre 3 anni di esperienza o competenze di livello L2, e copre operazioni avanzate in NovaLCT, utilizzo pratico dell’intera gamma prodotti Novastar, configurazioni per scenari complessi come schermi extra-large o irregolari, bassa latenza, trasmissioni a lunga distanza, soluzioni 3D e sistemi con backup completo; al termine consente di operare su progetti LED complessi e su attività di supporto tecnico avanzato.', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-102', 'NOVASTAR', 'AV311', 'Expert in LED Screen Implementation', 'COMING SOON', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-103', 'NOVASTAR', 'AV311', 'Professional in LED Screen Calibration', 'È una certificazione specialistica intermedia del programma Novastar Certified Engineer (NCE), pensata per formare tecnici capaci di eseguire la calibrazione dei LED display. È rivolta soprattutto a technical support engineer, after-sales engineer e rental engineer che hanno già ottenuto la certificazione L1, e copre fondamenti della calibrazione, diverse modalità di correzione, workflow operativi come CLB-Cabinet, CLB-Screen e Calcube, oltre all’analisi dei casi e al troubleshooting; al termine consente di operare in autonomia nella calibrazione di luminosità e colore dei display LED SMD.', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-104', 'NOVASTAR', 'AV311', 'Specialist in LED Screen Calibration', 'È una certificazione avanzata del programma Novastar Certified Engineer (NCE), pensata per formare figure senior specializzate nella calibrazione dei LED display. È rivolta soprattutto a tecnici, post-sales engineer e rental engineer con certificazione NCE L2 o almeno 3 anni di esperienza, e copre calibrazione SMD e COB, schermi irregolari, calibrazione ad alta precisione e full grayscale, uso dei software CLB e Calcube, oltre al troubleshooting delle problematiche di calibrazione; al termine consente di operare in autonomia su servizi avanzati di calibrazione COB e su schermi LED di forma irregolare.', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-105', 'NOVASTAR', 'AV311', 'Expert in LED Screen Calibration', 'COMING SOON', 'In-Class', null, 0, array['spec_eng_av']),
  ('KU-C-106', 'POWERSOFT', 'AV102', 'Powersoft 101I', 'È un breve corso tecnico di taglio pratico dedicato al software ArmoníaPlus, utile per imparare a creare un progetto Install, utilizzare le funzioni di Dynamic Music Distribution e progettare interfacce App e Web View. Il focus è sulle attività di configurazione e design del sistema per la gestione e il controllo della distribuzione musicale.', 'E-Learning', '03:00', 0, array['core_av','core_doc']),
  ('KU-C-107', 'POWERSOFT', 'AV202', 'Powersoft 201i', 'È un corso tecnico on-demand di livello intermedio dedicato ai sistemi Install Powersoft, pensato per chi vuole approfondire la progettazione di progetti avanzati in ArmoníaPlus. Copre la creazione e gestione di sistemi Install più complessi, oltre a temi come audio networking, configurazione di reti e integrazione con controlli di terze parti, ampliando le competenze sviluppate nel corso 101i e fornendo una comprensione più completa del software e delle funzionalità di sistema.', 'E-Learning', '03:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-108', 'Q-SYS', 'AV102', 'Q-SYS Architect', 'È un corso introduttivo in aula su Q-SYS Architect, pensato per chi vuole iniziare a progettare sistemi nell’ecosistema Q-SYS senza necessità di competenze di programmazione o commissioning. È indicato per consulenti AV, end user, pre-sales engineer e progettisti, e copre signal flow di base, differenza tra sistemi centralizzati e distribuiti, design di spazi meeting/collaboration e panoramica delle principali famiglie QSC come processing, I/O, amplificatori e diffusori. Non richiede prerequisiti, dura 4 ore in aula e riconosce 2 crediti AVIXA CTS al superamento dell’assessment finale.', 'Webinar (Prase)', '02:00', 0, array['core_av','core_doc']),
  ('KU-C-109', 'Q-SYS', 'AV102', 'Q-SYS Sales Professional', 'È un corso on-demand pensato per figure commerciali e sales, utile per capire come presentare e valorizzare la piattaforma Q-SYS senza richiedere competenze tecniche o esperienza con Q-SYS Designer. Copre i principi della piattaforma, panoramica hardware e software, controllo integrato con audio e video, value proposition cloud-first ed ecosistema partner, con un approccio orientato a vendita e posizionamento della soluzione. Non richiede prerequisiti, dura circa 3 ore e riconosce 1,5 crediti AVIXA CTS al completamento.', 'In-Class', '03:00', 0, array['core_av','core_doc']),
  ('KU-C-110', 'Q-SYS', 'AV102', 'Q-SYS Level 0', 'Corso introduttivo per accedere al Level 1', 'E-Learning', null, 0, array['core_av','core_doc']),
  ('KU-C-111', 'Q-SYS', 'AV202', 'Q-SYS Level 1', 'È un corso tecnico di livello base-intermedio su Q-SYS, pensato per chi vuole imparare a configurare, distribuire e fare troubleshooting dei sistemi sulla piattaforma. Copre Core Manager, Administrator e Configurator, controllo e UCI, audio playback, test & measurement, mixer, soluzioni di conferencing, telephony deployment, monitoraggio cloud e aspetti di sicurezza, con un approccio orientato a commissioning operativo e preparazione all’esame finale; per completarlo è richiesto prima il corso Q-SYS Level Zero.', 'E-Learning', '08:00', 0, array['adv_eng_av','adv_doc']),
  ('KU-C-112', 'Q-SYS', 'AV202', 'Q-SYS Level 2', 'È un corso live di livello intermedio-avanzato su Q-SYS, pensato per chi vuole consolidare le competenze dopo il Level 1 attraverso attività pratiche di deployment, creazione di interfacce utente, introduzione a networking e controllo. Ogni partecipante lavora su Core Q-SYS e periferiche di controllo dedicate, con un approccio fortemente hands-on e un esame finale di troubleshooting basato su scenari reali di installazione. Richiede come prerequisiti Q-SYS Level One e Q-SYS Control 101, può essere seguito in presenza o da remoto ed assegna 8 crediti AVIXA CTS al completamento.', 'In-Class (Prase)', '16:00', 0, array['adv_eng_av']),
  ('KU-C-113', 'Q-SYS', null, 'Q-SYS Quantum', null, 'In-Class', '03:00', null, '{}'),
  ('KU-E-037', 'SHURE', 'AV102', 'Collaboration & Conferencing Certification - Level 1', 'GROUP ID: CCLevel1 | È un percorso introduttivo pensato per team tecnici che gestiscono infrastrutture AV/IT aziendali e per i Channel Partner Shure che supportano i clienti nella scelta delle soluzioni audiovisive più adatte per spazi meeting e ambienti di apprendimento. L’obiettivo è fornire una base chiara per orientarsi tra esigenze tecniche, consulenza e selezione delle tecnologie AV corrette.', 'Certification', '08:00', 0, array['core_av','core_doc']),
  ('KU-E-038', 'SHURE', 'AV202', 'Collaboration & Conferencing Certification - Level 2', 'GROUP ID: CCLevel2 | È un percorso tecnico pensato per tecnici esperti e ingegneri AV/IT che affrontano attività più complesse di progettazione, setup e configurazione dei sistemi, con l’obiettivo di realizzare soluzioni integrate e affidabili. È rivolto a figure con una preparazione già solida e richiede il completamento del Livello 1 come prerequisito per accedere ai corsi.', 'Certification', '08:00', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-E-039', 'SHURE', 'AV202', 'Pro Level 1', 'È un percorso pensato per professionisti audio emergenti, tecnici AV junior, assistenti audio, stagisti e team commerciali, ideale per costruire una base iniziale sulle competenze e sui concetti fondamentali del settore. Si rivolge a figure all’inizio del percorso professionale o che vogliono rafforzare la propria comprensione tecnica per operare con maggiore sicurezza nel mondo audio e AV.', 'Certification', '04:30', 0, array['adv_eng_av']),
  ('KU-E-040', 'SHURE', 'AV202', 'Pro Level 2', 'È un percorso ideale per audio engineer, tecnici live sound (FOH e mix), specialisti corporate e AV coordinator, pensato per figure che operano già in contesti professionali e vogliono consolidare competenze pratiche nella gestione audio. Si rivolge a ruoli coinvolti nella configurazione, ottimizzazione e gestione operativa dei sistemi in ambienti live, corporate ed eventi.', 'Certification', '07:00', 0, array['adv_eng_av']),
  ('KU-E-041', 'SHURE', 'AV308', 'Pro Level 3', 'È un percorso pensato per professionisti AV esperti, RF coordinator, system designer, senior AV engineer e specialisti dell’integrazione, ideale per figure che gestiscono progetti complessi e vogliono approfondire competenze avanzate. Si rivolge a ruoli coinvolti nella progettazione, ottimizzazione e gestione di sistemi AV evoluti, con particolare attenzione agli aspetti di integrazione e coordinamento tecnico.', 'Certification', '14:00', 0, array['spec_eng_av']),
  ('KU-C-114', 'SHURE', 'AV202', 'Microflex Complete Wireless Technical Enablement Training', 'È un corso on-demand di taglio tecnico-specialistico dedicato al sistema Shure Microflex Complete Wireless (MXCW), utile per approfondirne funzionalità, setup e configurazione. Copre caratteristiche e vantaggi, casi d’uso tipici, componenti hardware con montaggio e collegamenti, configurazione di base e configurazione avanzata tramite interfacce web, con un approccio orientato a installazione, commissioning e gestione operativa del sistema.', 'E-Learning', '01:30', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-115', 'SHURE', 'AV202', 'MXA310 Table Array Technical Enablement', 'È un breve corso tecnico di taglio pratico dedicato al microfono da tavolo Shure MXA310, utile per imparare come installarlo e configurarlo correttamente. Il focus è sulle attività essenziali di setup e messa in servizio del dispositivo in ambienti meeting e conferencing.', 'E-Learning', '00:30', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-116', 'SHURE', 'AV202', 'Microflex Wireless neXt 4 and 8 Channel Technical Enablement', 'È un corso tecnico-specialistico on-demand dedicato al sistema Shure Microflex Wireless neXt a 4 e 8 canali, utile per approfondirne funzioni, componenti hardware, interfaccia utente e software Designer. Il percorso, suddiviso in 4 moduli, mostra in modo pratico come configurare il sistema, con casi d’uso, suggerimenti operativi e best practice per l’installazione e la messa in servizio; per ottenere il credito formativo è necessario superare l’esame finale con almeno l’80%.', 'E-Learning', '00:45', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-117', 'SHURE', 'AV102', 'MXA920 Ceiling Array Microphone Technical Enablement', 'È un breve corso tecnico di taglio pratico dedicato al microfono array da soffitto Shure MXA920, utile per imparare come installarlo e configurarlo correttamente. Il focus è sulle attività essenziali di setup e messa in servizio del nuovo modello di punta della gamma di microfoni di rete Shure.', 'E-Learning', '00:45', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-118', 'SHURE', 'AV202', 'Fast Track: BLX Wireless System', 'È un breve corso on-demand di taglio introduttivo dedicato al sistema wireless Shure BLX, utile per capire componenti, funzioni e possibilità d’uso della piattaforma. È pensato per applicazioni come strumenti musicali, fitness e parlato, e fornisce una panoramica pratica delle caratteristiche e capacità del sistema per aiutare a scegliere e usare correttamente la soluzione BLX.', 'E-Learning', '00:15', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-119', 'SHURE', 'AV202', 'SLX-D+ Technical Enablement', 'È un corso tecnico-specialistico on-demand dedicato al sistema wireless Shure SLX-D+, pensato per utenti, tecnici e professionisti audio che vogliono imparare a configurarlo, metterlo in servizio e usarlo con sicurezza. Copre setup e configurazione, oltre a funzioni avanzate come ShowLink Ease, Digital Feedback Reduction, encryption, audio summing e integrazione con Wireless Workbench Mobile, con l’obiettivo di facilitare sia la migrazione da SLX-D sia il primo deployment di SLX-D+ in modo efficace.', 'E-Learning', '00:30', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-120', 'SHURE', 'AV202', 'Fast Track: QLX-D Wireless System', 'È un breve corso on-demand di taglio introduttivo dedicato al sistema wireless digitale Shure QLX-D, utile per conoscere caratteristiche, componenti e funzionamento generale della piattaforma. Il focus è offrire una panoramica chiara del sistema, così da comprenderne meglio le possibilità d’uso in ambito audio professionale.', 'E-Learning', '00:15', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-121', 'SHURE', 'AV202', 'ANX4 Technical Overview', 'È un corso tecnico-specialistico on-demand dedicato al ricevitore wireless scalabile Shure ANX4, pensato per chi vuole imparare a gestire licenze, configurazione hardware e deployment di sistemi wireless ad alta densità di canali. Copre attivazione e trasferimento delle licenze, utilizzo con trasmettitori Axient Digital o ULX-D, setup del ricevitore e workflow operativi, con l’obiettivo di sfruttare al meglio ANX4 in installazioni wireless professionali complesse.', 'E-Learning', '00:35', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-122', 'SHURE', 'AV202', 'Axient Digital PSM Technical Enablement', 'È un corso tecnico-specialistico on-demand dedicato a Shure Axient Digital PSM, pensato per professionisti audio, fonici e staff tecnico che vogliono approfondire in modo pratico e tecnico il sistema. Si basa sulle nozioni introduttive del modulo overview e offre indicazioni più dettagliate su setup, configurazione e utilizzo operativo di Axient Digital PSM, con l’obiettivo di sviluppare una comprensione più completa della piattaforma in contesti professionali.', 'E-Learning', '00:50', 0, array['adv_presales_av','adv_eng_av']),
  ('KU-C-123', 'TECNOFIRE', 'SEC101', 'Corso Pre sales', 'Corso Pre-Sales Prodotti con nozioni sulla normativa antincendio', 'In-Class', '08:00', 0, array['core_sec','core_doc']),
  ('KU-C-124', 'TECNOFIRE', 'SEC203', 'Corso Tecnico 1 Livello', 'Corso Tecnico programmazione Base Centrale Incendio', 'In-Class', '08:00', 0, array['adv_doc','adv_field']),
  ('KU-C-125', 'TECNOFIRE', 'SEC203', 'Corso Tecnico 2 Livello', 'Corso Tecnico programmazione Avanzato Centrale Incendio', 'In-Class', '08:00', 0, array['adv_field']),
  ('KU-C-126', 'TELEVIC', 'AV102', 'Meeting Foundamentals', 'È un breve corso e-learning introduttivo dedicato ai fondamenti dei sistemi di conferenza, utile per capire cosa sia un conference system, quali siano i diversi tipi di meeting e quali componenti siano necessari per realizzare una sala conferenze efficace. Il percorso fornisce una panoramica delle funzionalità principali e delle possibili configurazioni, aiutando a orientarsi tra le esigenze tipiche degli ambienti meeting e le soluzioni tecnologiche disponibili.', 'E-Learning', '01:00', 0, array['core_av']),
  ('KU-C-127', 'TELEVIC', 'AV102', 'Televic Foundation', 'È un breve corso e-learning introduttivo dedicato alle soluzioni Televic per meeting e conferenze, utile per comprendere l’azienda, la sua visione e il portafoglio prodotti. Il percorso offre una panoramica delle tecnologie Televic, delle principali linee di prodotto e delle funzionalità di smart audio e controllo, con l’obiettivo di aiutare a identificare e applicare le soluzioni più adatte ai diversi scenari di meeting e conferencing.', 'E-Learning', '01:00', 0, array['core_av']),
  ('KU-C-128', 'TELEVIC', 'AV309', 'Technical Training Level 1', null, null, null, 0, array['spec_eng_av']),
  ('KU-C-129', 'TELEVIC', 'AV309', 'Technical Training Level 2', null, null, null, 0, array['spec_eng_av']),
  ('KU-C-130', 'YAMAHA', 'AV101', 'General Knowledge | Beginner | 1. Sound and Hearing Basics', 'È un breve corso introduttivo sui principi fondamentali dell’audio, pensato per fornire una base chiara su come viene prodotto il suono, come si propagano le onde sonore e come funziona la percezione uditiva umana. Il percorso aiuta a comprendere i concetti essenziali dell’acustica e dell’audio, risultando utile sia per principianti sia per professionisti che vogliono rafforzare le proprie conoscenze tecniche.', 'E-Learning', '00:30', 0, array['core_av']),
  ('KU-C-131', 'YAMAHA', 'AV101', 'General Knowledge | Beginner | 2. Basics of Sound Wave', 'È un breve corso introduttivo sulle onde sonore e sull’acustica, pensato per fornire una base solida sui principi fisici del suono. Copre temi come proprietà delle onde, frequenza, ampiezza, fase, interazioni tra onde e tipologie di onde sonore, con l’obiettivo di sviluppare una comprensione utile sia per chi inizia sia per chi opera in ambiti come audio engineering, produzione musicale e discipline tecniche correlate.', 'E-Learning', '00:45', 0, array['core_av']),
  ('KU-C-132', 'YAMAHA', 'AV101', 'General Knowledge | Beginner | 3. Sound intensity, loudness, and decibels', 'È un breve corso introduttivo dedicato a intensità sonora, percezione del volume e decibel, pensato per fornire una base chiara sia sugli aspetti fisici sia su quelli percettivi del suono. Copre la differenza tra forza del suono e loudness, il modo in cui l’orecchio umano elabora i segnali audio, il range dinamico, oltre ai concetti di esponenti, logaritmi e definizione del decibel, fondamentali per comprendere correttamente le misure audio.', 'E-Learning', '00:30', 0, array['core_av']),
  ('KU-C-133', 'YAMAHA', 'AV101', 'General Knowledge | Beginner | 4. Sound Intensity and Loudness: Levels and Calculations', 'È un breve corso introduttivo di taglio tecnico dedicato al concetto di livello in acustica, utile per collegare in modo pratico pressione sonora, intensità sonora e loudness percepita. Copre SPL e valori di riferimento, rapporto tra pressione e intensità, curve di uguale sensazione sonora, filtri di pesatura come l’A-weighting, calcoli in decibel e principali scale audio come dBu, dBV e dBFS, con l’obiettivo di fornire una comprensione chiara e applicabile ai contesti audio reali.', 'E-Learning', '00:45', 0, array['core_av']),
  ('KU-C-134', 'YAMAHA', 'AV101', 'General Knowledge | Advanced | Speech Intelligibility: Can You Hear Me?', 'È un breve corso introduttivo dedicato all’intelligibilità del parlato, utile per capire perché una comunicazione chiara dipenda non solo dal sistema AV, ma anche dalle caratteristiche dell’ambiente in cui viene utilizzato. Spiega come si misura l’intelligibilità e quali interventi possono contribuire a migliorarla, offrendo una base pratica per progettare e valutare meglio spazi e soluzioni audio.', 'E-Learning', '00:55', 0, array['core_av']),
  ('KU-C-135', 'YAMAHA', null, 'General Knowledge | Advanced | Connecting AES67 Devices', null, 'E-Learning', '00:15', null, '{}'),
  ('KU-C-136', 'YAMAHA', null, 'Distributed Audio​ and Public Address​ Courses | Beginner | Yamaha Certified ProAV Specialist - Level 1', null, 'E-Learning', '01:00', null, '{}'),
  ('KU-C-137', 'YAMAHA', null, 'Distributed Audio​ and Public Address​ Courses | Beginner | Better Sound for Commercial Installations', null, 'E-Learning', '01:30', null, '{}'),
  ('KU-C-138', 'YAMAHA', null, 'DM3 Series: Digital Mixing Console', null, 'E-Learning', '01:30', null, '{}'),
  ('KU-C-139', 'YAMAHA', null, 'DM7 Series: Digital Mixing Console', null, 'E-Learning', '03:00', null, '{}')
on conflict (id) do update set
  brand       = excluded.brand,
  gruppo      = excluded.gruppo,
  nome        = excluded.nome,
  descrizione = excluded.descrizione,
  erogazione  = excluded.erogazione,
  durata      = excluded.durata,
  prezzo      = excluded.prezzo,
  paths       = excluded.paths;

-- ============================================================
-- 4. Corsi ritirati
--    Non si cancellano: le certificazioni e le assegnazioni già
--    registrate devono continuare a trovare il loro corso.
--    Sta qui e non nella INSERT sopra perché l'upsert non tocca `attivo`:
--    così rilanciare lo script non li fa tornare in catalogo.
-- ============================================================

-- KU-C-034 "Avigilon Unity Video" (in aula, 8h): Kaplet lo considera un
-- doppione di KU-C-033 "Avigilon Unity Video8" (e-learning, 21h).
update public.corsi_catalogo set attivo = false where id = 'KU-C-034';

-- Controllo finale: 183 in tabella, 182 ancora in catalogo
select
  count(*)                          as corsi_in_tabella,
  count(*) filter (where attivo)    as corsi_in_catalogo,
  count(*) filter (where not attivo) as corsi_ritirati
from public.corsi_catalogo;
